Description of calc_scal
Home > coriolis > bigone > PROJETS > UVMAT.new > calc_scal.m
calc_scal
PURPOSE
'calc_scal': defines scalars and calculate them from stored fields. OBSOLETE to replace by calc_field
SYNOPSIS
function [Scal]=calc_scal(ScalName,DataIn)
DESCRIPTION
'calc_scal': defines scalars and calculate them from stored fields. OBSOLETE to replace by calc_field
---------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
RUN_STLIN 'RUN_STLIN': combine velocity fields for stereo PIV
read_scalar 'read_scalar': reads and calculates the vort div or any scalar from a file
read_vel 'read_vel': reads one or two velocity fields and associated parameters from a file or a pair of files.
series 'series': master function associated to the GUI series.m for analysis field series
sub_field 'sub_field': combines two input fields + mask for uvmat
uvmat 'uvmat': function associated with the interface 'uvmat.fig' for images and field visualization
varname_generator 'varname_generator': defines the names of constants and variable fields to read in the netcdf files