Description of document_field
Home > coriolis > bigone > PROJETS > UVMAT.new > document_field.m
document_field
PURPOSE
'document_field': provides the appropriate heading to a Matlab structure representing physical fields
SYNOPSIS
function FieldData=document_field(Data_in)
DESCRIPTION
'document_field': provides the appropriate heading to a Matlab structure representing physical fields
 if isfield(Data_in,'ListVarName')
     if ~isempty(Data_in.ListVarName)
     return
     end
 end
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_field 'get_field': display variables and attributes from a Netcdf file, and plot selected fields
plot_field 'plot_field': plot any field with the structure of the uvmat package
proj_field 'proj_field': projects the field on a projection object