Description of editxml
Home > . > editxml.m
editxml
PURPOSE
'editxml': function for editing xml files using a xml schema (associated with the GUI editxml.fig)
SYNOPSIS
function varargout = editxml(varargin)
DESCRIPTION
'editxml': function for editing xml files using a xml schema (associated with the GUI editxml.fig)
------------------------------------------------------------------------
 function heditxml=editxml(inputfile)
OUTPUT: heditxml: graphic handle of the GUI
INPUT: inputfile:  name of an xml file
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  Copyright Joel Sommeria, 2008, LEGI / CNRS-UJF-INPG, sommeria@coriolis-legi.org.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     This file is part of the toolbox UVMAT.
     UVMAT is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.
     UVMAT is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License (file UVMAT/COPYING.txt) for more details.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CROSS-REFERENCE INFORMATION
This function calls:
ListDir 'ListDir': scan the structure of the directory tree (for dataview.m)
cell2tab 'cell2tab': transform a Matlab cell in a character array suitable for display in a table
dataview TEST 'dataview': function for scanning directories in a campaign (TEST)
read_xls 'read_xls': function for reading and displaying Excel files
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
warndlg_uvmat 'warndlg_uvmat': display warning message (error, warning, confirmation) in a given figure
This function is called by:
civ 'civ': function associated with the interface 'civ.fig' for PIV, spline interpolation and stereo PIV (patch)
civ_3D 'civ_3D': function associated with the interface 'civ_3D.fig' for PIV in volume
dataview TEST 'dataview': function for scanning directories in a campaign (TEST)
read_xls 'read_xls': function for reading and displaying Excel files
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SUBFUNCTIONS
function editxml_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = editxml_OutputFcn(hObject, eventdata, handles)
function list_element_Callback(hObject, eventdata, handles)
function move_up_Callback(hObject, eventdata, handles)
function element_value_Callback(hObject, eventdata, handles)
function browser_Callback(hObject, eventdata, handles)
function CurrentFile_Callback(hObject, eventdata, handles)
function [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,nodeinput)
function [element,subelem]=get_xml(t,path,xs_element,node,xs_subelem)
function update_list(handles,path,xs_element,element,node,xs_subelem,subelem)
function SAVE_Callback(hObject, eventdata, handles)
function t=set_element(t,RootUid,node,key,value)
function element_attr_val_Callback(hObject, eventdata, handles)
function ADD_Callback(hObject, eventdata, handles)
function [Data,testsimple]=displ_xml(handles,t,root_uid,DataIn,heditxml)
function update_ref_list(hh,xs_element,element,node,xs_subelem,subelem)
function replicate_Callback(hObject, eventdata, handles)
function HELP_Callback(hObject, eventdata, handles)
function Export_Callback(hObject, eventdata, handles)
function pushbutton9_Callback(hObject, eventdata, handles)
SOURCE CODE
%'editxml': function for editing xml files using a xml schema (associated with the GUI editxml.fig)
%------------------------------------------------------------------------
% function heditxml=editxml(inputfile)
%
%OUTPUT: heditxml: graphic handle of the GUI
%
%INPUT: inputfile:  name of an xml file
%
%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
%  Copyright Joel Sommeria, 2008, LEGI / CNRS-UJF-INPG, sommeria@coriolis-legi.org.
%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
%     This file is part of the toolbox UVMAT.
%
%     UVMAT is free software; you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation; either version 2 of the License, or
%     (at your option) any later version.
%
%     UVMAT is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License (file UVMAT/COPYING.txt) for more details.
%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
function varargout = editxml(varargin)
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @editxml_OpeningFcn, ...
                   'gui_OutputFcn',  @editxml_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin & isstr(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before editxml is made visible.
function editxml_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to editxml (see VARARGIN)
% set(handles.replicate,'String',['copy';'<---'])
if nargin
    CurrentFile=varargin{1}
else
    CurrentFile=[];
end
% if exist('varargin') & length(varargin)>=1
%     CurrentFile=cell2mat(varargin{1});
% else
%     CurrentFile=[];
% end
% Choose default command line output for editxml
handles.output = hObject;
% set(hObject,'Units','pixel')
if exist(CurrentFile,'file')
    [PathName,Nme,FileExt]=fileparts(CurrentFile);
    if isequal(FileExt,'.xls')
        DataIn.hfig_xls=read_xls(CurrentFile);% DataIn.hfig_xls=handle of the Excel display figure
        DataIn.CurrentUid=1;
        figpos=get(hObject,'Position');%position of the editxml interface
        figposunit=get(hObject,'Units');%unity used to indicate position
        newfigpos=[figpos(1)-0.5*figpos(3) figpos(2) figpos(3) figpos(4)];
        set(DataIn.hfig_xls,'Units',figposunit)
        set(DataIn.hfig_xls,'Position',newfigpos); %set position of the Excel display figure
        set(hObject,'UserData',DataIn)
    else
        set(handles.CurrentFile,'String',CurrentFile)
        CurrentFile_Callback(hObject, eventdata, handles)
    end
end
% Update handles structure
guidata(hObject, handles);
%----------------------------------------------------------------
% --- Outputs from this function are returned to the command line.
function varargout = editxml_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Executes on selection change in list_element.
function list_element_Callback(hObject, eventdata, handles)
global t xs t_ref
CurrentFile=get(handles.CurrentFile,'String');
bla=get(hObject,'String');
ind=get(hObject,'Value');
list=get(hObject,'UserData');
NewRootUid=list.uid(ind);
heditxml=get(hObject,'Parent');
DataIn=get(heditxml,'UserData');
if ~isempty(xs)
    xs_node=list.xs_uid(ind);%xs_node of the subelement #ind
    [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,xs_node);
    [element,subelem]=get_xml(t,path,xs_element,NewRootUid,xs_subelem);
    update_list(handles,path,xs_element,element,NewRootUid,xs_subelem,subelem);
    if xs_element.subtest
        DataIn.CurrentUid=[DataIn.CurrentUid NewRootUid];%record new current uid
        DataIn.xs_CurrentUid=[DataIn.xs_CurrentUid xs_node];%record the new curent schema uid
    end
%     %update the import file display
%     if isfield(DataIn,'h_ref')&ishandle(DataIn.h_ref)
%         tag0_ref=find(t_ref,['/' path '/' xs_element.key]);
%         node_ref=list.index(ind);
%         if length(tag0_ref)<node_ref
%             node_ref=length(tag0_ref);
%         end
%         [ref_element,ref_subelem]=get_xml(t_ref,path,xs_element,node_ref,xs_subelem);
%         update_ref_list(DataIn.h_ref,xs_element,ref_element,node_ref,xs_subelem,ref_subelem);
%     end
set(get(hObject,'Parent'),'UserData',DataIn);
else%no schema
    [DataIn,testsimple]=displ_xml(handles,t,NewRootUid,DataIn,get(hObject,'parent'));
    if ~testsimple
        DataIn.CurrentUid=[DataIn.CurrentUid NewRootUid];%record new current uid
        set(get(hObject,'Parent'),'UserData',DataIn);
    end
end
%-------------------------------------------------
% --- Executes on button press in move_up.
function move_up_Callback(hObject, eventdata, handles)
global t xs t_ref
set(handles.export_list,'Value',1);%
set(handles.export_list,'String','');% empty the export list
CurrentFile=get(handles.CurrentFile,'String');
CurrentElement=get(handles.CurrentElement,'String');
heditxml=get(handles.move_up,'parent');
test_root=0;
DataIn=get(heditxml,'UserData');
if isfield(DataIn,'CurrentUid')&length(DataIn.CurrentUid)>1
    nodeup=DataIn.CurrentUid(end-1);
    DataIn.CurrentUid(end)=[];
else
    nodeup=[];
end
if isempty(xs)
    if isempty(nodeup)
        test_root=1;
    else
        DataIn=displ_xml(handles,t,nodeup,DataIn,heditxml);
    end
else
    xs_nodeup=[];
%     if isfield(DataIn,'xs_UpUid')
    if isfield(DataIn,'xs_CurrentUid')&length(DataIn.xs_CurrentUid)>1
%         xs_nodeup=DataIn.xs_UpUid
        xs_nodeup=DataIn.xs_CurrentUid(end-1);
        DataIn.xs_CurrentUid(end)=[];%uid of the root element in the schema
    end
    if isempty(xs_nodeup)
        test_root=1;
    else
        [xs_nodeup,path,xs_element,xs_subelem]=scan_schema(xs,xs_nodeup);
        [element,subelem]=get_xml(t,path,xs_element,nodeup,xs_subelem);
        update_list(handles,path,xs_element,element,nodeup,xs_subelem,subelem);
        %update the import file display
        if isfield(DataIn,'h_ref')&ishandle(DataIn.h_ref)
            [ref_element,ref_subelem]=get_xml(t_ref,path,xs_element,nodeup,xs_subelem);
            update_ref_list(DataIn.h_ref,xs_element,ref_element,nodeup,xs_subelem,ref_subelem);
        end
    end
    set(get(hObject,'parent'),'UserData',DataIn);
end
if test_root% we are a the root,
    testupfile=0;
    DataIn=get(get(hObject,'parent'),'UserData');
    if isfield(DataIn,'UpFile')&~isempty(DataIn.UpFile)
        [UpPath,UpName,UpExt]=fileparts(DataIn.UpFile{1});
        if isequal(UpExt,'.xml')
            set(handles.CurrentFile,'String',DataIn.UpFile{1})
            CurrentFile_Callback(handles.CurrentFile,[],handles)
            testupfile=1;
            DataIn.UpFile{1}={};
        end
    end
    if ~testupfile  %open the browser
        RootPath=fileparts(CurrentFile);
            [FileName, PathName]=uigetfile( ...
               {'*.xml', '(*.xml)';
                '*.xml',  '.xml files '; ...
                '*.*',  'All Files (*.*)'}, ...
                'Pick a file',RootPath); %file browser
            fileinput_new=fullfile(PathName,FileName);
            set(handles.CurrentFile,'String',fileinput_new)
            CurrentFile_Callback(handles.CurrentFile,[],handles)
     end
end
set(heditxml,'UserData',DataIn);
%---------------------------------------------------------
%edit element value
function element_value_Callback(hObject, eventdata, handles)
%----------------------------------------------------------
global t xs
if isequal(get(handles.element_value,'ForegroundColor'),[0.7 0.7 0.7])
    return% edit element desactivated (grey display)
end
list_enum=get(handles.element_value,'String');
list_index=get(handles.element_value,'Value');
if iscell(list_enum)
    value=list_enum{list_index};
else
    value=list_enum;
end
heditxml=get(handles.element_value,'Parent');
DataIn=get(heditxml,'UserData');
%create the current root element if needed
LengthElement=length(DataIn.CurrentUid);
FilledUid=find(DataIn.CurrentUid~=0);
LengthFilled=FilledUid(end);
for irank=LengthFilled+1:LengthElement
    attrib=attributes(xs,'get',DataIn.xs_CurrentUid(irank),1);
    [t,DataIn.CurrentUid(irank)]=add(t,DataIn.CurrentUid(irank-1),'element',attrib.val);
end
node_element=get(handles.element_value,'UserData');
element_key=get(handles.element_key,'String');
t=set_element(t,DataIn.CurrentUid(end),node_element,element_key,value);
set(heditxml,'UserData',DataIn)
%update the current listing
[nodeup,path,xs_element,xs_subelem]=scan_schema(xs,DataIn.xs_CurrentUid(end));
[element,subelem]=get_xml(t,path,xs_element,DataIn.CurrentUid(end),xs_subelem);
element_index=get(handles.list_element,'Value');
update_list(handles,path,xs_element,element,DataIn.CurrentUid(end),xs_subelem,subelem);
set(handles.list_element,'Value',element_index);
%
% % --- Executes on button press in inport_file.
% function inport_file_Callback(hObject, eventdata, handles)
% CurrentFile=get(handles.RefFile,'String');
% if isempty(CurrentFile)|isequal(CurrentFile,'')
%     CurrentFile=get(handles.CurrentFile,'String')
% end
% [FileName, PathName]=uigetfile(...
%        {'*.xml', '(*.xml)';
%         '*.xml',  '.xml files '; ...
%         '*.*',  'All Files (*.*)'}, ...
%         'Pick a file',CurrentFile); %file browser
% fileinput=fullfile(PathName,FileName);
% sizf=size(fileinput);
% if (~ischar(fileinput)|~isequal(sizf(1),1)),return;end% keep only character strings as input file name
% if exist(fileinput,'file')
%    set(handles.RefFile,'Visible','on')
%    set(handles.replicate,'Visible','on')
%    set(handles.RefFile,'String',fileinput)
%    RefFile_Callback(handles.RefFile, eventdata, handles)
% end
%------------------------------------------------------
% --- Executes on button press in browser.
function browser_Callback(hObject, eventdata, handles)
%-------------------------------------------------------
heditxml=get(hObject,'parent');%handle of the interface figure
DataIn=get(heditxml,'UserData');%get the current input xml file
CurrentFile=get(handles.CurrentFile,'String');
DataIn.Schema=[];%schema input file put to [] by default
[FileName, PathName]=uigetfile(...
       {'*.xml;*.xls','(*.xml,*.xls)';
        '*.xml',  '.xml files '; ...
        '*.xls',  '.xls files '; ...
        '*.*',  'All Files (*.*)'}, ...
        'Pick a file',CurrentFile); %file browser
CurrentFile=fullfile(PathName,FileName);
sizf=size(CurrentFile);
if (~ischar(CurrentFile)|~isequal(sizf(1),1)),return;end% keep only character strings as input file name
if exist(CurrentFile,'file')
%     set(handles.CurrentAttributes,'UserDataIn',PathName); %store the path to the xml file
    [CurPath,CurName,CurExt]=fileparts(CurrentFile);
    if isequal(CurExt,'.xls')
        if isfield(DataIn,'hfig_xls')&ishandle(DataIn.hfig_xls)
            [hfig_xls]=read_xls(CurrentFile,DataIn.hfig_xls);
        else
            [hfig_xls]=read_xls(CurrentFile);
        end
        figpos=get(heditxml,'Position');
        newfigpos=[figpos(1)-0.25*figpos(3) figpos(2) 0.5*figpos(3) 0.5*figpos(4)];
        set(hfig_xls,'Position',newfigpos)
    else
        set(handles.CurrentFile,'String',CurrentFile)
        CurrentFile_Callback(hObject, eventdata, handles)
     end
end
%------------------------------------
function CurrentFile_Callback(hObject, eventdata, handles)
global t xs
CurrentFile=get(handles.CurrentFile,'String');
heditxml=get(handles.CurrentFile,'parent');%handles of the inteface
DataIn=get(heditxml,'UserData');
t=xmltree(CurrentFile);%open the xml file
head_element=get(t,1);
if ~isfield(head_element,'name') | ~isfield(head_element,'attributes')
    warndlg_uvmat('root element of the .xml file not in correct format','ERROR')
end
head_name=head_element.name;
head_attr=head_element.attributes;% attribute of root gives the name of the associated schema
xstest=0;
for iattr=1:length(head_attr)
    if isequal(head_attr{iattr}.key,'xmlns:xsi')& isequal(head_attr{iattr}.val,'none')%no schema to read
         xs=[];
%          xstest=1;
    end
    if isequal(head_attr{iattr}.key,'xsi:noNamespaceSchemaLocation') & exist(head_attr{iattr}.val,'file')
        DataIn.Schema=head_attr{iattr}.val;
        xs=xmltree(DataIn.Schema);%open the associated schema file
        xstest=1;
    end
end
if xstest==0  %look for the corresponding schema in the directory PARAM_LINUX.xml or PARAM_WIN.xml
    head_name=get(t,1,'name');
    %Path to shemas:
    path_uvmat=which('editxml');% check the path detected for source file uvmat
    path_UVMAT=fileparts(path_uvmat); %path to UVMAT
    if isunix
        xmlparam=fullfile(path_UVMAT,'PARAM_LINUX.xml')
        if exist(xmlparam,'file')
            tparam=xmltree(xmlparam);
            sparam=convert(tparam);
            if isfield(sparam,'SchemaPath')
                schemapath=[fullfile(sparam.SchemaPath,head_name) '.xsd']
            end
        end
%         schemapath=['/coriolis/papillon/data/civbin/XML_SCHEMAS/' head_name '.xsd']%current dir for schema
    else
        xmlparam=fullfile(path_UVMAT,'PARAM_WIN.xml')
        if exist(xmlparam,'file')
            tparam=xmltree(xmlparam);
            sparam=convert(tparam)
            if isfield(sparam,'SchemaPath')
                schemapath=[fullfile(sparam.SchemaPath,head_name) '.xsd']
            end
        end
%         schemapath=['\\Papillon\data\civbin\XML_SCHEMAS\' head_name '.xsd']%current dir for schemas
    end
    if exist(schemapath,'file')
        xs=xmltree(schemapath);
    else
        warndlg_uvmat(['The xml schema for ' CurrentFile ' is unknown, check the schema path set in the xml file PARAM'],'ERROR')
        [FileName, PathName]=uigetfile( ...
       {'*.xsd', '(*.xsd)';
        '*.xsd',  '.xsd files '; ...
        '*.*',  'All Files (*.*)'}, ...
        ['Pick a .xsd schema'] ,schemapath); %file browser
        if ischar(PathName)&ischar(FileName)& exist(fullfile(PathName,FileName),'file')
            DataIn.Schema=fullfile(PathName,FileName);
            xs=xmltree(DataIn.Schema);%open the associated schema file
        else
            xs=[];
        end
    end
end
DataIn.CurrentUid=1;
if isempty(xs)
    displ_xml(handles,t,1,DataIn,get(hObject,'parent'));%no associated schema, default  display of the xml file
%    set(handles.inport_file,'Visible','off')
%    set(handles.RefFile,'Visible','off')
else
    DataIn.xs_CurrentUid=find(xs,'/xs:schema/xs:element');%uid of the root element in the schema
    [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,DataIn.xs_CurrentUid);%scan the schema at the root level
    [element,subelem]=get_xml(t,path,xs_element,1,xs_subelem);% read the corresponding xml data
    update_list(handles,path,xs_element,element,1,xs_subelem,subelem);%update the display of information on the interface
   % set(handles.inport_file,'Visible','on')
   % set(handles.RefFile,'Visible','on')
end
set(heditxml,'UserData',DataIn);%store the new input xml file name
%-------------------------------------------------------
%  function scan_schema: read the xml schema xs
%--------------------------------------------------------
%OUTPUT:
%nodeup: parent node of nodeinput
%path: path to nodeinput in the tree
%xs_element: element corresponding to nodeinput
    %xs_element.uid, =tag of the element in the schema (=nodeinput)
    %xs_element.key: key label of nodeinput
    %xs_element.type: type of data contained in the element
    %xs_element.annot: annotation of nodeinput
    %xs_element.attrib: list of accepted attributes keys for xs_element
    %xs_element.enum: enumeration, list of accepted values for nodeinput
    %xs_element.subtest: =1 if the element contains subelements in the schema, 0 else
%xs_subelement(k): subelement #k of xs_element
    %xs_subelem(k).node: node number in the schema
    %xs_subelem(k).key: key name of the element
    %xs_subelem(k).testsub: =1 if element contains subelements, 0 else
    %xs_subelem(k).minOccurs: =0 for a non mandatory element, =1 else
    %xs_subelem(k).maxOccurs
%
%INPUT:
%xs: schema xml tree
%nodeinput: tag of the current root element in the schema
function [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,nodeinput)
nodeup=[];
path=[];
xs_element.key=[];
xs_element.type=[];
xs_element.annot=[];
xs_element.attrib=[];
xs_element.subtest=0;
xs_element.enum={};
xs_subelem=[];%default
% get default nodeinput (root of the file) if not defined
if ~exist('nodeinput') | isempty(nodeinput)% we start at the root
    node=find(xs,'/xs:schema/xs:element');%description of the root element
else
    node=nodeinput;
end
xs_element.uid=node;
%get the key name and element_type of the element
node_content=get(xs,node);
if isempty(node_content),return,end;
if ~isempty(node_content) & isfield(node_content,'attributes')
    attrib=node_content.attributes;
    for iattr=1:length(attrib)
        struct=attrib{iattr};
        if isequal(struct.key,'name')
            xs_element.key=struct.val; % read element key name
        elseif isequal(struct.key,'type')
            xs_element.type=struct.val; % read element key name
        end
    end
end
%get the parent node of nodeinput
if ~isempty(node_content)
    nodeup=get(xs,node,'parent');%move up to the parent in the tree
    if ~isempty(nodeup)
        nodeup=get(xs,nodeup(1),'parent');%move up to the parent in the tree
        if isequal(nodeup,[])
            %OUVRIR FICHIER AMONT
            up=0;
        else
            nodeup=get(xs,nodeup(1),'parent');%move up to the parent in the tree
        end
    end
end
%get the path to 'nodeinput' in the schema
up=1;
path=[];
if ~isempty(nodeup)
    attrib=attributes(xs,'get',nodeup,1);
    path=attrib.val;
    nodeup2=nodeup;
    while up==1;
        nodeup2=get(xs,nodeup2(1),'parent');%move up to the parent in the tree
        nodeup2=get(xs,nodeup2(1),'parent');%move up to the parent in the tree
        if isempty(nodeup2)
            up=0;
        else
            nodeup2=get(xs,nodeup2(1),'parent');%move up to the parent in the tree
            if isempty(nodeup2)
                up=0;
            else
                attrib=attributes(xs,'get',nodeup2,1);
                path=[attrib.val '/' path];
            end
        end
    end
end
%explore the subtree in the schema file
node1=children(xs,node); %find the children of the root element
test_sub=0; %no subtree in the .xml file by default
comment='';
element={};
minOccurs={};
maxOccurs={};
testsub={};
list_menu={};
text={};
if ~isempty(node1)
  for i=1:length(node1)
    nodename1=get(xs,node1(i),'name');
    node2=children(xs,node1(i));
    if isequal(nodename1,'xs:annotation')
         for j=1:length(node2)
            nodename2=get(xs,node2(j),'name');
            if isequal(nodename2,'xs:documentation')
                node3=children(xs,node2(j));
                xs_element.annot=get(xs,node3,'value');%read annotation
            end
        end
    % pour les elements
    elseif isequal(nodename1,'xs:simpleType')
        for j=1:length(node2)
            nodename2=get(xs,node2(j),'name');
            if isequal(nodename2,'xs:restriction')
                node3=children(xs,node2(j));
                for k=1:length(node3)
                    nodename3=get(xs,node3(k),'name');
                    if isequal(nodename3,'xs:enumeration')
                        node3_content=get(xs,node3(k));
                        attr=node3_content.attributes;
                        for m=1:length(attr)
                            struct=attr{m};
                            if isequal(struct.key,'value')
                                xs_element.enum{k}=struct.val; % read enumeration
                            end
                        end
                   end
               end
            end
        end
     elseif isequal(nodename1,'xs:complexType')
         for j=1:length(node2)
             nodename2=get(xs,node2(j),'name');
             if isequal(nodename2,'xs:attribute')
                 node_content=get(xs,node2(j));
                 attr=node_content.attributes;
                 for k=1:length(attr)
                    struct=attr{k};%read attributes
                    if isequal(struct.key,'name')
                        xs_element.attrib=struct.val; %read attributes of main node
                    end
                 end
             elseif isequal(nodename2,'xs:sequence')
                 xs_element.subtest=1;
                 node3=children(xs,node2(j));%nodes of the sequence
                 for k=1:length(node3)
                     xs_subelem(k).node=node3(k);
                     xs_subelem(k).testsub=0;%default
                     node_content=get(xs,node3(k));
                     xs_subelem(k).minOccurs=1; %default
                     xs_subelem(k).maxOccurs=1; %default
%                      pref{k}=[]; %default
                     if isequal(node_content.name,'xs:element')
                        attr=node_content.attributes;
%                         attr{:}.key
                        for l=1:length(attr)
                            if isequal(attr{l}.key,'name')
                                xs_subelem(k).key=attr{l}.val;%name of the element
                            elseif isequal(attr{l}.key, 'minOccurs')
                                xs_subelem(k).minOccurs=attr{l}.val;
                            elseif isequal(attr{l}.key, 'maxOccurs')
                                xs_subelem(k).maxOccurs=attr{l}.val;
                            end
                        end
                     end
                     node4=children(xs,node3(k));
                     for l=1:length(node4)
                        res=get(xs,node4(l),'name');
                        if isequal(res,'xs:complexType')%look whether the element k contains a subtree
                           node5=children(xs,node4(l));
                           for m=1:length(node5)
                               res2=get(xs,node5(m),'name');
                               if isequal(res2,'xs:sequence')
                                    xs_subelem(k).testsub=1; %flag for the existence of a subtree
                               end
                           end
                        end
                     end
                 end
             end
         end
     end
  end
end
% look for predefined types
if length(xs_element.type)>=3 & (xs_element.type([1:3])~='xs:')
    node_type=find(xs,'/xs:schema/xs:simpleType')
    for i=1:length(node_type)
        content=get(xs,node_type(i));
        nodeattr=content.attributes;
        if ~isempty(nodeattr) & isequal(nodeattr{1}.key,'name') & isequal(nodeattr{1}.val,xs_element.type)
            node1=children(xs,node_type(i));
            node2=find(xs,node1,'name','xs:restriction');
%             nodename1=find(xs,
            node3=children(xs,node2);
            node4=find(xs,node3,'name','xs:enumeration');
            for ienum=1:length(node4)
                struct2=get(xs,node4(ienum));
                enumval=struct2.attributes;
                xs_element.enum{ienum}=enumval{1}.val;
            end
        end
     end
end
%--------------------------------------------------------
%OUTPUT:
%element.val: value of the current element, =[] in the absence of chardata value
%node: node (iud) of the element in t
%element.attr_key{iattr}: attribute key #iattr of the current element
%element.attr_val{iattr}: attribute value #iattr of the current element
%element.attrup: %structure containing the attributes of the element, including the ones unheritated from parent nodes
%subelem(iline).val : value of subelement # iline, concatenated with corresponding attributes
%subelem(iline).xsindex: index k of the subelement #iline in the list xs_subelem of the schema
%subelem(iline).index: index of the subelement #iline inside its xs_subelement, =0 when the xs_subelement is absent in t
%INPUT:
%t: xml tree
%path: path to the current element in the schema
%xs_element: current element in the schema
    %xs_element.key: key label
    %xs_element.type: type of data contained in the element
    %xs_element.annot: annotation of nodeinput
    %xs_element.attrib: list of accepted attributes keys for xs_element
    %xs_element.enum: enumeration, list of accepted values
    %xs_element.subtest: =1 if the element contains subelements in the schema, 0 else
%index: index of the element, =1 in case of single occurence in xs_element,=0 in case of missing element
%xs_subelem(k): subelement #k of the current element in the schema
    %xs_subelem(k).node: node iud of the
    %xs_subelem(k).key: key name of the subelement #k in the schema
    %xs_subelem(k).testsub: =1 if element contains subelements, 0 else
    %xs_subelem(k).minOccurs
    %xs_subelem(k).maxOccurs
function [element,subelem]=get_xml(t,path,xs_element,node,xs_subelem)
element.attr_key='';%default
element.attr_val='';%default
element.val='';
% element.type='';
% element.testmanual=testmanual %inheritates the input manual editing flag by default
subelem=[]; %default
attrup=[];
% node=[];
% %find the element properties in the xml file
if node >= 1
    elem_struct=get(t,node);
    if ~xs_element.subtest
        elem_contents=get(t,elem_struct.contents);
        if isempty(elem_contents)
            element.val=[];
        else
            element.val=elem_contents.value
        end
    end
    if isfield(elem_struct,'attributes')
        elem_attr=elem_struct.attributes;
        for iattr=1:length(elem_attr)
            element.attr_key{iattr}=elem_attr{iattr}.key ;
            element.attr_val{iattr}=elem_attr{iattr}.val;
%             attrup=setfield(attrup,elem_attr{iattr}.key,elem_attr{iattr}.val);
           breakdetect=find(elem_attr{iattr}.key=='/'| elem_attr{iattr}.key==':'| elem_attr{iattr}.key=='.');% find '/'
           if isempty(breakdetect)
%                 comline=['attrup.' elem_attr{iattr}.key '=' elem_attr{iattr}.val ';']
                eval(['attrup.' elem_attr{iattr}.key '=''' elem_attr{iattr}.val ''';'])
           end
        end
    end
end
%get the parent node attributes
up=1;
if node>0
    nodeup=node;
    while up==1;
        nodeup=get(t,nodeup,'parent');%move up to the parent in the tree
        if isempty(nodeup)
            up=0;
        else
            nodeup_content=get(t,nodeup);
            attrib=nodeup_content.attributes;
            for iattr=1:length(attrib)
                key=attrib{iattr}.key;
                breakdetect=find(key=='/'| key==':'| key=='.');% find '/'
                if ~isfield(attrup,key) & isempty(breakdetect)
                   eval(['attrup.' key '=''' attrib{iattr}.val ''';'])
                end
            end
        end
    end
    element.attrup=attrup;
end
%find the subelement properties in the xml file
if xs_element.subtest
   iline=0;
   for k=1:length(xs_subelem)%node2: list of subelements in the sub-sequence
%     attr=attributes(xs,'get',node2(i),1);%
%     element=attr.val;%name of the element
     tag=find(t,['/' path '/' xs_element.key '/' xs_subelem(k).key]);%look for the corresponding element node in the .xml tree
     struct_element=get(t,tag);%get the content of the element
     if isempty(struct_element)
         iline=iline+1;
         subelem(iline).uid=0;
         subelem(iline).xsindex=k;
         subelem(iline).index=0;
%          subelem(iline).testmanual=element.testmanual;% inheritates the manual editing flag by default
         if isequal(xs_subelem(k).minOccurs,'0')
             subelem(iline).val='[]';%element value not mandatory in the schema
         else
             subelem(iline).val='[MISSING]';%element value mandatory in the schema
         end
%          subelem(iline).attrup=attrup; %inheritated attributes
     elseif isequal(length(struct_element),1)
         contents=get(t,struct_element.contents);
         iline=iline+1;
         subelem(iline).uid=tag;
         subelem(iline).xsindex=k;
         subelem(iline).index=1;
%          subelem(iline).testmanual=element.testmanual;%
         if isfield(contents,'value') & ~isempty(contents.value)
             subelem(iline).val=contents.value;
         elseif xs_subelem(k).testsub
             subelem(iline).val='';
         elseif isequal(xs_subelem(k).minOccurs,0)
             subelem(iline).val='[]';%element value not mandatory in the schema
         else
             subelem(iline).val='[MISSING]';%element value mandatory in the schema
         end
%          subelem(iline).attrup=attrup; %inheritated attributes
         if isfield(struct_element,'attributes')
            element_attr=struct_element.attributes;
            attr_display=[];
            for iattr=1:length(element_attr)
%                 attr_display{iline}=[attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
                subelem(iline).val=[subelem(iline).val attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
%                 subelem(iline).attrup=setfield(subelem(iline).attrup,element_attr{iattr}.key,element_attr{iattr}.val);
            end
         end
     else%case of a multiple element
         for subindex=1:length(struct_element)
             contents=get(t,struct_element{subindex}.contents);
             iline=iline+1;
             subelem(iline).index=subindex;%index of the element
             subelem(iline).xsindex=k;
%              subelem(iline).testmanual=element.testmanual;%
             if isfield(contents,'value')& ~isempty(contents.value)
                 subelem(iline).val=contents.value;
             elseif xs_subelem(k).testsub
                 subelem(iline).val='';
             else
                 subelem(iline).val='[]';
             end
%              subelem(iline).attrup=attrup; %inheritated attributes
             if isfield(struct_element{subindex},'attributes')
                element_attr=struct_element{subindex}.attributes;
                attr_display=[];
                for iattr=1:length(element_attr)
%                     attr_display{iline}=[attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
                    subelem(iline).val=[subelem(iline).val attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
%                     subelem(iline).attrup=setfield(subelem(iline).attrup,element_attr{iattr}.key,element_attr{iattr}.val);
                end
            end
        end
     end
  end
end
%-------------------------------------
%updates the interface
function update_list(handles,path,xs_element,element,node,xs_subelem,subelem)
%-----------------------------
if xs_element.subtest% we list the sub-elements of root
    set(handles.export_list,'Value',1)
    set(handles.export_list,'String','')%flush the export list
    set(handles.CurrentElement,'String',[path '/' xs_element.key])
%     title_element.key=[path '/' xs_element.key];
%     if ~isempty(path)
%         xsnode_index=get(handles.list_element,'UserDataIn');
%         ind=get(handles.list_element,'Value');
%         title_element.index=xsnode_index(2,ind);
%     else
%         title_element.index=1;
%     end
%     title_element.xsnode=xs_element.uid;
%     title_element.node=node;
%     set(handles.CurrentFile,'UserDataIn',title_element)%element corresponding to the title
    set(handles.CurrentAnnotation,'String',xs_element.annot)
    attr_col=[];
    testedit=0;% cannot edit elements by default
    for iattr=1:length(element.attr_key)
%          if isequal(element.attr_key{iattr},'source') & isequal(element.attr_val{iattr},'manual')
%             testedit=1;
%         end
        attr_col=strvcat(attr_col,[element.attr_key{iattr} ' = ' element.attr_val{iattr}]);
    end
    set(handles.CurrentAttributes,'String',attr_col)
    pref_col='';
    key_col='';
    equal_sign='';
    val_col='';
    for iline=1:length(subelem)
        xsindex=subelem(iline).xsindex;
        index(iline)=subelem(iline).index;
        subuid=subelem(iline).uid;
        if isempty(subuid)
            list.uid(iline)=0;
        else
            list.uid(iline)=subuid;
        end
        node(iline)=xs_subelem(xsindex).node;
%         testmanual(iline)=subelem(iline).testmanual;
        ikey=xs_subelem(xsindex).key;
        if xs_subelem(xsindex).testsub
            ival=[' + ' subelem(iline).val];
        else
            ival=[' = ' subelem(iline).val];
        end
        key_col=strvcat(key_col,ikey);
        val_col=strvcat(val_col,ival);
    end
    list_element=[key_col val_col];
    set(handles.list_element,'String',list_element)
    set(handles.list_element,'Value',1)
    list.xs_uid=node;
    list.index=index;
    set(handles.list_element,'UserData',list)
    set(handles.element_attrib,'Visible','off')
    set(handles.element_key,'Visible','off')
    set(handles.element_value,'Visible','off')
else % we edit an element
    export_list=get(handles.export_list,'String');%export list
    testadd=1;
    for ilist=1:length(export_list)
        if isequal(xs_element.key,export_list{ilist})
            testadd=0;
            break
        end
    end
    if testadd
        export_list=[export_list;{xs_element.key}];
        ilist=length(export_list);
    end
    set(handles.export_list,'String',export_list)
    if iscell(element.val)
        element_val=element.val{1};
    else
        element_val=element.val;
    end
    set(handles.element_value,'String',element_val)
    export_val=get(handles.export_list,'UserData');
    export_val{ilist}=element_val;
    set(handles.export_list,'UserData',export_val);
    set(handles.element_annot,'String',xs_element.annot)
    set(handles.element_type,'String',['type:  ' xs_element.type])
    attr_col=[];
    testedit=0;% cannot edit element by default
    for iattr=1:length(element.attr_key)
%         if isequal(element.attr_key{iattr},'source') & isequal(element.attr_val{iattr},'manual')
%             testedit=1;
%         end
        attr_col=strvcat(attr_col,[element.attr_key{iattr} ' = ' element.attr_val{iattr}]);
    end
    set(handles.element_attrib,'String',attr_col)
    set(handles.element_key,'String',xs_element.key)
    if isempty(xs_element.enum)
        set(handles.element_value,'Value',1)
        set(handles.element_value,'Style','edit')
    else % case of an enumeration of possible values
         list_enum=[];
         list_val=[];
         for ienum=1:length(xs_element.enum)
             list_enum{ienum,1}=xs_element.enum{ienum};
             if isequal(xs_element.enum{ienum},element_val)
                 list_val=ienum;
             end
         end
         if isempty(list_val)
             list_enum{length(xs_element.enum)+1,1}=['[' element_val ']'];%show the non-valid element between brackets
             list_val=length(xs_element.enum)+1;
         end
         set(handles.element_value,'Style','popupmenu')
         set(handles.element_value,'String',list_enum)
         set(handles.element_value,'Value',list_val)
     end
     if isempty(element.val)
         testedit=1;%allow element editing if value is missing
     end
     set(handles.element_attrib,'Visible','On')
     set(handles.element_key,'Visible','On')
     set(handles.element_value,'Visible','On')
end
set(handles.element_value,'UserData',node)
if ~testedit && isfield(element,'attrup') & isfield(element.attrup,'source')&& ~isequal(element.attrup.source,'manual')
     set(handles.element_value,'Enable','inactive')
else
    set(handles.element_value,'Enable','on')
end
% --- Executes on button press in SAVE.
function SAVE_Callback(hObject, eventdata, handles)
global t
DataIn=get(get(handles.SAVE,'parent'),'UserData');
CurrentFile=get(handles.CurrentFile,'String');
if isfield(DataIn,'Schema')
if ~isempty(DataIn.Schema)% update ref to schema
    attrxsd=attributes(t,'get',1);
    setest=0;
    for iattr=1:length(attrxsd)
        if isequal(attrxsd{iattr}.key,'xsi:noNamespaceSchemaLocation')
            t= attributes(t,'set',1,iattr,'xsi:noNamespaceSchemaLocation',DataIn.Schema);
            setest=1;
        end
    end
    if setest==0;
        t=attributes(t,'add',1,'xmlns:xsi','http://www.w3.org/2001/XMLSchema-instance');
        t= attributes(t,'add',1,'xsi:noNamespaceSchemaLocation',DataIn.Schema);
    end
end
end
copyfile(CurrentFile,[CurrentFile '.bak']);
save(t,CurrentFile);
%-------------------------------------
% creates and/or set values to an element in t
%t: xml tree
%RootUid: uid of t under which we introduce an element
%node: uid of the element that we correct, if =0, a new element is created
%key: key name of the element
%value: new value of the element
function t=set_element(t,RootUid,node,key,value)
%create the subelement if needed
if isequal(node,0)
   [t,node]= add(t,RootUid,'element',key);
end
node_chardata=children(t,node); %corresponding data node
if isempty(node_chardata)%if the data does not exist in t, create it
    t=add(t,node,'chardata',value);
elseif isequal(length(node_chardata),1)&isequal(get(t,node_chardata,'type'),'chardata')% update only a simple element with 'chardata'
    t=set(t,node_chardata,'value',value);%modify existing data
end
attr=attributes(t,'get',node);
if isempty(attr)
    t=attributes(t,'add',node,'source','manual');%indicate a manual eidting
end
% --- Executes on selection change in element_attr_val.
function element_attr_val_Callback(hObject, eventdata, handles)
% hObject    handle to element_attr_val (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = get(hObject,'String') returns element_attr_val contents as cell array
%        contents{get(hObject,'Value')} returns selected item from element_attr_val
% --- Executes on button press in ADD.
function ADD_Callback(hObject, eventdata, handles)
% hObject    handle to ADD (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%----------------------------------------
%read an xml file without schema
function [Data,testsimple]=displ_xml(handles,t,root_uid,DataIn,heditxml)
Data=DataIn;%default
if ~isfield(Data,'CurrentUid')
    Data.CurrentUid=[];
end
CurrentFile=get(handles.CurrentFile,'String');
%display the current element
root_element=get(t,root_uid);
uidparent=root_uid;
if isfield(root_element,'name')
    CurrentElement=root_element.name;
    while ~isequal(uidparent,1)%while the first level has not been reached
        uidparent=parent(t,uidparent);
        dirdat=get(t,uidparent);
        if isfield(dirdat,'name')
            CurrentElement=[dirdat.name '/' CurrentElement];
        end
    end
    set(handles.CurrentElement,'String',CurrentElement)
end
list_uid=children(t,root_uid);
%case of a single element
testsimple=0;
filedat=[];
if ~isempty(list_uid)
    filedat=get(t,list_uid(1))
    if isfield(filedat,'type') & isequal(filedat.type,'chardata') &isfield(filedat,'value')
        testsimple=1;%simple element
    end
end
%attributes of the current element
nbattrib= attributes(t,'length',root_uid);
testopen=0;
attr_col=[];
for iattr=1:nbattrib
    attr= attributes(t,'get',root_uid,iattr);
    if isequal(attr.key,'source')% look for 'source' attribute
1000         if isequal(attr.val,'file')%if the source is 'file', look for the path and open it
1001            if isfield(filedat,'type') & isequal(filedat.type,'chardata') &isfield(filedat,'value')
1002                cur_file=filedat.value;
1003                uidparent=root_uid;%initialization
1004                while ~isequal(uidparent,1)%while the first level has not been reached
1005                     uidparent=parent(t,uidparent);
1006                     dirdat=get(t,uidparent);
1007                     if isfield(dirdat,'type') & isequal(dirdat.type,'element') & isfield(dirdat,'name')
1008                         nbattrib_up= attributes(t,'length',uidparent);
1009                         for iattr_up=1:nbattrib_up
1010                             attr= attributes(t,'get',uidparent,iattr_up);
1011 %                             if isequal(attr.key,'source')&isequal(attr.val,'directory')% look for 'source' attribute
1012                               if isequal(attr.key,'DirName')
1013                                  cur_file=fullfile(attr.val,cur_file);
1014                              end
1015                         end
1016                     end
1017                end
1018                RootPath=fileparts(CurrentFile);%path to the current .xml file
1019                cur_file=fullfile(RootPath,cur_file)
1020                set(handles.CurrentAttributes,'UserData',cur_file)%will be searched by uvmat
1021                [path,fil,ext]=fileparts(cur_file);
1022                if ~exist(cur_file,'file')
1023                    warndlg_uvmat(['non-existent link file' cur_file],'ERROR') % A FAIRE: propose to updtate the .xml file
1024                    return
1025                elseif isequal(ext,'.xml')
1026                    if ~isfield(Data,'UpFile')
1027                        Data.UpFile={CurrentFile};
1028                    else
1029                        Data.UpFile=[{CurrentFile};Data.UpFile];
1030                    end
1031                    set(heditxml,'UserData',Data)
1032                    set(handles.CurrentFile,'String',cur_file)
1033                    CurrentFile_Callback(handles.CurrentFile, [], handles)
1034                else
1035                    if isequal(get(heditxml,'Tag'),'browser'); %if editxml has been called as a browser
1036                        set(heditxml,'Tag','idle')% signal for uvmat browser
1037                    else
1038                        uvmat({cur_file}); %open the link fiel with uvmat
1039                    end
1040                    return
1041                end
1042            end
1043        %elseif isequal(attr.val,'dir') A FAIRE : check directory
1044        %else A FAIRE: edit the element
1045         end
1046     end
1047     attr_col=strvcat(attr_col,[attr.key ' = ' attr.val]);
1048 end
1049 set(handles.CurrentAttributes,'String',attr_col)
1050
1051 %list subtree
1052 if ~testsimple
1053     list_element=[];
1054 %      Data.CurrentUid=[Data.CurrentUid root_uid]%record new current uid
1055     for iline=1:length(list_uid)
1056         element=get(t,list_uid(iline));
1057         if isfield(element,'type')&isequal(element.type,'element')
1058              list_element{iline,2}=element.name;
1059              child_uid=children(t,list_uid(iline));
1060              subelem=get(t,child_uid);
1061              if isfield(subelem,'type')& isfield(subelem,'value') & isequal(subelem.type,'chardata')
1062                 data_read=subelem.value;
1063                 list_element{iline,3}=['= ' data_read];
1064             end
1065             if iscell(subelem)|(isfield(subelem,'type')&isequal(subelem.type,'element'))
1066                 list_element{iline,1}='+ ';%sign for subtree existence
1067             else
1068                 list_element{iline,1}='  ';
1069             end
1070             nbattr=attributes(t,'length',list_uid(iline));
1071             if nbattr==1
1072                 attr=attributes(t,'get',list_uid(iline));
1073                 list_element{iline,4}=[attr.key '='];
1074                 list_element{iline,5}=attr.val;
1075             elseif nbattr>1
1076                 for iattr=1:nbattr
1077                     attr=attributes(t,'get',list_uid(iline),iattr);
1078                     list_element{iline,2+2*iattr}=[attr.key '='];
1079                     list_element{iline,3+2*iattr}=attr.val;
1080                 end
1081             end
1082         end
1083     end
1084     set(handles.list_element,'Value',1)%select the first line of list_element by default
1085     set(handles.list_element,'String',cell2tab(list_element,' '))
1086     list.uid=list_uid;
1087     set(handles.list_element,'UserData',list)
1088 end
1089 %---------------------------------------------------------
1090 %-------------------------------------
1091 %updates the interface
1092 function update_ref_list(hh,xs_element,element,node,xs_subelem,subelem)
1093 %-----------------------------
1094 pref_col='';
1095 key_col='';
1096 equal_sign='';
1097 val_col='';
1098 for iline=1:length(subelem)
1099     xsindex=subelem(iline).xsindex;
1100     indexcur=subelem(iline).index;
1101     subuid=subelem(iline).uid;
1102         if isempty(subuid)
1103              RefDataIn.uid(iline)=0;
1104         else
1105              RefDataIn.uid(iline)=subuid;
1106         end
1107     index(iline)=indexcur;
1108     node(iline)=xs_subelem(xsindex).node;
1109 %         testmanual(iline)=subelem(iline).testmanual;
1110     ikey=xs_subelem(xsindex).key;
1111     if xs_subelem(xsindex).testsub
1112         ival=[' + ' subelem(iline).val];
1113     else
1114         ival=[' = ' subelem(iline).val];
1115     end
1116     key_col=strvcat(key_col,ikey);
1117     val_col=strvcat(val_col,ival);
1118 end
1119 RefDataIn.xs_uid=node;
1120 list_element=[key_col val_col];
1121 siztext=size(list_element);
1122 set(hh,'Value',[1:siztext(1)])
1123 set(hh,'String',list_element)
1124 set(hh,'UserData',RefDataIn)
1125
1126 %
1127 % function RefFile_Callback(hObject, eventdata, handles)
1128 % global t_ref xs
1129 % t_ref=xmltree(get(hObject,'String'));%open the xml file fileinput
1130 % heditxml=get(hObject,'parent');
1131 % DataIn=get(get(hObject,'parent'),'UserData');
1132 % % set(heditxml,'Units','pixel')
1133 % figpos=get(heditxml,'Position')
1134 % % title_element=get(handles.element_cur,'UserDataIn');
1135 % % xs_node=xsnode_index(1,ind);
1136 % % index_chosen=xsnode_index(2,ind);
1137 % if isfield(DataIn,'fig_ref')&ishandle(DataIn.fig_ref)
1138 %     figure(DataIn.fig_ref);
1139 % else
1140 %     DataIn.fig_ref=figure;
1141 % end
1142 % set(DataIn.fig_ref,'Name',get(hObject,'String'))
1143 % set(DataIn.fig_ref,'MenuBar','none')
1144 % newfigpos=[figpos(1)+figpos(3) figpos(2)+0.4*figpos(4) 0.5*figpos(3) 0.3*figpos(4)];
1145 % set(DataIn.fig_ref,'Units','normalized')
1146 % set(DataIn.fig_ref,'Position',newfigpos)
1147 % DataIn.h_ref=uicontrol('Style','listbox', 'Max',2,'Units','pixel','Position', [0 0 newfigpos(3) newfigpos(4)], ...
1148 %         'FontName','FixedWidth','Tag','listbox');
1149 % if isfield(DataIn,'xs_CurrentUid');
1150 %     xs_CurrentUid=DataIn.xs_CurrentUid(end);
1151 % else
1152 %     DataIn.xs_CurrentUid=find(xs,'/xs:schema/xs:element');%uid of the root element in the schema
1153 % end
1154 % [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,xs_CurrentUid(end));
1155 % xs_element.key
1156 % tag0=find(t_ref,['/' path '/' xs_element.key]);
1157 % if length(tag0)>=1
1158 %     CurrentRefNode=tag0(1);%chose the first occurence of the element
1159 % else
1160 %     CurrentRefNode=0;
1161 % end
1162 % [ref_element,ref_subelem]=get_xml(t_ref,path,xs_element,CurrentRefNode,xs_subelem);
1163 % update_ref_list(DataIn.h_ref,xs_element,ref_element,CurrentRefNode,xs_subelem,ref_subelem);
1164 % siztext=size(get(DataIn.h_ref,'String'));
1165 % set(DataIn.h_ref,'Value',[1:siztext(1)]); %select the whole list by default
1166 % set(heditxml,'UserData',DataIn)
1167 % set(handles.ref_data,'Value',siztext(1)); %select the whole list by default
1168 % 'TESTimport'
1169 % title_element=get(handles.element_cur,'UserDataIn')
1170 % xs_node=title_element.xsnode;%uid of the element in the schema
1171 % node=title_element.node;
1172 % t=flush(t,node);%removes the corresponding subtree in t
1173 % [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,xs_node);%scan the schema
1174 % tag0=find(t_import,['/' path '/' xs_element.key])
1175 % if isempty(tag)
1176 %     errordlg(['element /' path '/' xs_element.key ' not found in' fileinput])
1177 %     return
1178 % end
1179 % % [element_import,node_import]=get_xml(t_import,path,xs_element,1,xs_subelem);% read the corresponding xml data
1180 % node2_import=children(t_import,tag0);
1181 % % t_import=branch(t_import,node_import);% extract branch of the new file
1182 % % %removes the corresponding subtree in t
1183 % for inode=1:length(node2_import)
1184 %     struct=get(t_import,node2_import(inode))
1185 %     if isfield(struct,'type') & isfield(struct,'name')%if the node is an elmeent type
1186 %         node3_import=children(t_import,node2_import(inode))
1187 %        [t,newuid]=add(t,node,struct.type,struct.name);
1188 %        for inode2=1:length(node3_import)
1189 %            struct2=get(t_import,node3_import(inode2))
1190 %            if isequal(struct2.type,'chardata')
1191 %                 t=add(t,newuid,'chardata',struct2.value);
1192 %             end
1193 %         end
1194 %     end
1195 % end
1196 % --- Executes on button press in replicate.
1197 function replicate_Callback(hObject, eventdata, handles)
1198 global xs  t
1199
1200 export_list=get(handles.export_list,'String');
1201 export_val=get(handles.export_list,'UserData');
1202 heditxml=get(handles.replicate,'parent');
1203 Data=get(heditxml,'UserData')
1204
1205 hdataview=findobj(allchild(0),'Name','dataview')
1206 if isempty(hdataview)
1207     hdataview=dataview;
1208     return
1209 end
1210 hhdataview=guidata(hdataview);
1211 CurrentPath=get(hhdataview.CurrentFile,'String');
1212 ListExperiments=get(hhdataview.ListExperiments,'String');
1213 Value=get(hhdataview.ListExperiments,'Value');
1214 if ~isequal(Value,1)
1215     ListExperiments=ListExperiments(Value);
1216 end
1217 ListDevices=get(hhdataview.ListDevices,'String');
1218 Value=get(hhdataview.ListDevices,'Value');
1219 if ~isequal(Value,1)
1220     ListDevices=ListDevices(Value);
1221 end
1222 ListRecords=get(hhdataview.ListRecords,'String');
1223 Value=get(hhdataview.ListRecords,'Value');
1224 if ~isequal(Value,1)
1225     ListRecords=ListRecords(Value);
1226 end
1227 % uvmat('runplus_Callback',hObject,eventdata,handleshaxes)
1228 [ListDevices,ListRecords,ListXml,List]=ListDir(CurrentPath,ListExperiments,ListDevices,ListRecords);
1229 ListXml=get(hhdataview.ListXml,'String');
1230 Value=get(hhdataview.ListXml,'Value');
1231 if isequal(Value,1)
1232     warndlg_uvmat('you need to select the xml files to edit','ERROR')
1233     return
1234 end
1235 ListXml=ListXml(Value);%list of
1236 for iexp=1:length(List.Experiment)
1237     ExpName=List.Experiment{iexp}.name;
1238     if isfield(List.Experiment{iexp},'Device')
1239         for idevice=1:length(List.Experiment{iexp}.Device)
1240             DeviceName=List.Experiment{iexp}.Device{idevice}.name;
1241             if isfield(List.Experiment{iexp}.Device{idevice},'xmlfile')
1242                 for ixml=1:length(List.Experiment{iexp}.Device{idevice}.xmlfile)
1243                     FileName=List.Experiment{iexp}.Device{idevice}.xmlfile{ixml};
1244                     for ilistxml=1:length(ListXml)
1245                         if isequal(FileName,ListXml{ilistxml})
1246                             xmlfullname=fullfile(CurrentPath,ExpName,DeviceName,FileName);
1247                             t_export=xmltree(xmlfullname);
1248                             rootelement=get(t_export,1,'name');
1249                             uidlist=Data.CurrentUid;
1250                             if isequal(rootelement,get(t,1,'name'))
1251                                 backupfile=xmlfullname;
1252                                 testexist=2;
1253                                 while testexist==2
1254                                    backupfile=[backupfile '~'];
1255                                    testexist=exist(backupfile,'file');
1256                                 end
1257                                 [success,message]=copyfile(xmlfullname,backupfile);%make backup
1258                                 if ~isequal(success,1)
1259                                     warndlg_uvmat(['Error in the backup of ' xmlfullname],'ERROR')
1260                                     return
1261                                 end
1262                                 findstr=['/' rootelement];
1263                                 uid_export(1)=1;
1264                                 % fill the root elements if absent
1265                                 for index=2:length(uidlist)
1266                                     name_t=get(t,uidlist(index),'name')
1267                                     findstr=[findstr '/' name_t]
1268                                     uid=find(t_export,findstr)
1269                                     if isempty(uid)
1270                                         [t_export,uid_export(index)]=add(t_export,uid_export(index-1),'element',name_t);
1271                                     else
1272                                         uid_export(index)=uid;
1273                                     end
1274                                 end
1275                                 % chardata......
1276                             end
1277                             break
1278                         end
1279                     end
1280 %                     [Title,test]=check_heading(Currentpath,Campaign,ExpName,DeviceName,[],FileName,SubCampaignTest);
1281 %                     if test
1282 %                         [List.Experiment{iexp}.Device{idevice}.xmlfile{ixml} ' , Heading updated']
1283 %                     end
1284                 end
1285              elseif isfield(List.Experiment{iexp}.Device{idevice},'Record')
1286                 for irecord=1:length(List.Experiment{iexp}.Device{idevice}.Record)
1287                     RecordName=List.Experiment{iexp}.Device{idevice}.Record{irecord}.name;
1288                     if isfield(List.Experiment{iexp}.Device{idevice}.Record{irecord},'xmlfile')
1289                         for ixml=1:length(List.Experiment{iexp}.Device{idevice}.Record{irecord}.xmlfile)
1290                             FileName=List.Experiment{iexp}.Device{idevice}.Record{irecord}.xmlfile{ixml};
1291                             for ilistxml=1:length(ListXml)
1292                                 if isequal(FileName,ListXml{ilistxml})
1293                                     xmlfullname=fullfile(CurrentPath,ExpName,DeviceName,RecordName,FileName)
1294                                     break
1295                                 end
1296                             end
1297 %                             [Title,test]=check_heading(Currentpath,Campaign,ExpName,DeviceName,RecordName,FileName,SubCampaignTest);
1298 %                             if test
1299 %                                 [FileName ' , Heading updated']
1300 %                             end
1301                         end
1302                     end
1303                 end
1304             end
1305         end
1306     end
1307 end
1308 return
1309 %%%%%%%%%%% A REVOIR
1310 % Copier la liste des elements selectionnés dans dataview
1311 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1312 %ANCIEN:
1313 heditxml=get(hObject,'parent');
1314 DataIn=get(heditxml,'UserData');
1315 if ~isfield(DataIn,'h_ref')
1316     DataIn.h_ref=[];
1317 end
1318 if ~ishandle(DataIn.h_ref)
1319     errordlg('no source file opened for import')
1320     return
1321 end
1322 %create the current root element if needed
1323 LengthElement=length(DataIn.CurrentUid);
1324 FilledUid=find(DataIn.CurrentUid~=0);
1325 LengthFilled=FilledUid(end);
1326 for irank=LengthFilled+1:LengthElement
1327     attrib=attributes(xs,'get',DataIn.xs_CurrentUid(irank),1);
1328     [t,DataIn.CurrentUid(irank)]=add(t,DataIn.CurrentUid(irank-1),'element',attrib.val);
1329 end
1330
1331 %copy list of subelements
1332 RefDataIn=get(DataIn.h_ref,'UserData');
1333 list=get(handles.list_element,'UserData');%=,[node;index]
1334 for ilist=get(DataIn.h_ref,'Value')
1335     node_content=get(xs,RefDataIn.xs_uid(ilist));
1336     if ~isempty(node_content) & isfield(node_content,'attributes')
1337         attrib=node_content.attributes;
1338         for iattr=1:length(attrib)
1339             struct=attrib{iattr};
1340             if isequal(struct.key,'name')
1341                 key=struct.val; % read element key name
1342             end
1343         end
1344     end
1345     value='';
1346     if ~isequal(RefDataIn.uid(ilist),0)
1347         child_uid=children(t_ref,RefDataIn.uid(ilist));
1348         if isequal(length(child_uid),1)
1349             content=get(t_ref,child_uid);
1350             if isfield(content,'type') &isfield(content,'value')& isequal(content.type,'chardata')
1351                 value=content.value;
1352             end
1353         end
1354     end
1355     t=set_element(t,DataIn.CurrentUid(end),list.uid(ilist),key,value);
1356 end
1357 set(heditxml,'UserData',DataIn)
1358 %update the current listing
1359 [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,DataIn.xs_CurrentUid(end));
1360 [element,subelem]=get_xml(t,path,xs_element,DataIn.CurrentUid(end),xs_subelem);
1361 update_list(handles,path,xs_element,element,DataIn.CurrentUid(end),xs_subelem,subelem);
1362 % t=set_xml(t,xs_DataIn,subelem)
1363 %edit list of subelments:
1364
1365 %A REVOIR
1366 % xsnode_index=get(handles.list_element,'UserDataIn')
1367 % xs_node=xsnode_index(1,ind);
1368 % RefDataIn=get(handles.ref_data,'UserDataIn');
1369 % subelem=RefDataIn.subelem;
1370 % xsnode_index=get(handles.list_element,'UserDataIn');%data on the xs_nodes of the subelements
1371 % ref_list=get(handles.ref_data,'Value');%selected indices in the list of reference subelements
1372 % xs_node=xsnode_index(1,ref_list);%xs_nodes of the selected subelements
1373 % % index_chosen=xsnode_index(2,ref_list);% indices in the list of occurence for a subelement
1374 % % for ilist=ref_list
1375 % ilist=1;
1376 % while icontinue
1377 %     'TESTCOPY'
1378 %     [nodeup,path,xs_element,xs_subelem]=scan_schema(xs,xs_node(ilist))
1379 %     xs_subelem.key
1380 %     tsub=subelem(ilist).tsub
1381 %     xsnode_index(2,ilist)
1382 %     [ref_elem,ref_node,ref_subelem]=get_xml(tsub,'',xs_element,1,xs_subelem)
1383 %     ref_subelem.val
1384 %     testedit= ~isfield(element.attrup,'source') | isequal(element.attrup.source,'manual') %| element vide
1385 %
1386 %
1387 %     icontinue=0
1388 % end
1389 % function [element,node,subelem]=get_xml(t,path,xs_element,node,xs_subelem)
1390 % element.attr_key='';%default
1391 % element.attr_val='';%default
1392 % element.val='';
1393 % % element.type='';
1394 % % element.testmanual=testmanual %inheritates the input manual editing flag by default
1395 % subelem=[]; %default
1396 % attrup=[];
1397 % % node=[];
1398 %
1399 % % %find the element properties in the xml file
1400 % if node >= 1
1401 %     elem_struct=get(t,node);
1402 %     if ~xs_element.subtest
1403 %         elem_contents=get(t,elem_struct.contents);
1404 %         if isempty(elem_contents)
1405 %             element.val=[];
1406 %         else
1407 %             element.val=elem_contents.value
1408 %         end
1409 %     end
1410 %     if isfield(elem_struct,'attributes')
1411 %         elem_attr=elem_struct.attributes;
1412 %         for iattr=1:length(elem_attr)
1413 %             element.attr_key{iattr}=elem_attr{iattr}.key ;
1414 %             element.attr_val{iattr}=elem_attr{iattr}.val;
1415 % %             attrup=setfield(attrup,elem_attr{iattr}.key,elem_attr{iattr}.val);
1416 %            breakdetect=find(elem_attr{iattr}.key=='/'| elem_attr{iattr}.key==':'| elem_attr{iattr}.key=='.');% find '/'
1417 %            if isempty(breakdetect)
1418 % %                 comline=['attrup.' elem_attr{iattr}.key '=' elem_attr{iattr}.val ';']
1419 %                 eval(['attrup.' elem_attr{iattr}.key '=''' elem_attr{iattr}.val ''';'])
1420 %            end
1421 %         end
1422 %     end
1423 % end
1424 % %get the parent node attributes
1425 % up=1
1426 % if node>0
1427 %     nodeup=node;
1428 %     while up==1;
1429 %         nodeup=get(t,nodeup,'parent');%move up to the parent in the tree
1430 %         if isempty(nodeup)
1431 %             up=0;
1432 %         else
1433 %             nodeup_content=get(t,nodeup);
1434 %             attrib=nodeup_content.attributes;
1435 %             for iattr=1:length(attrib)
1436 %                 key=attrib{iattr}.key;
1437 %                 breakdetect=find(key=='/'| key==':'| key=='.');% find '/'
1438 %                 if ~isfield(attrup,key) & isempty(breakdetect)
1439 %                    eval(['attrup.' key '=''' attrib{iattr}.val ''';'])
1440 %                 end
1441 %             end
1442 %         end
1443 %     end
1444 %     element.attrup=attrup;
1445 % end
1446 % %find the subelement properties in the xml file
1447 % if xs_element.subtest
1448 %    iline=0;
1449 %    for k=1:length(xs_subelem)%node2: list of subelements in the sub-sequence
1450 % %     attr=attributes(xs,'get',node2(i),1);%
1451 % %     element=attr.val;%name of the element
1452 %      tag=find(t,['/' path '/' xs_element.key '/' xs_subelem(k).key]);%look for the corresponding element node in the .xml tree
1453 %      struct_element=get(t,tag);%get the content of the element
1454 %      if isempty(struct_element)
1455 %          iline=iline+1;
1456 %          subelem(iline).xsindex=k;
1457 %          subelem(iline).index=0;
1458 % %          subelem(iline).testmanual=element.testmanual;% inheritates the manual editing flag by default
1459 %          if isequal(xs_subelem(k).minOccurs,0)
1460 %              subelem(iline).val='[]';%element value not mandatory in the schema
1461 %          else
1462 %              subelem(iline).val='[MISSING]';%element value mandatory in the schema
1463 %          end
1464 % %          subelem(iline).attrup=attrup; %inheritated attributes
1465 %      elseif isequal(length(struct_element),1)
1466 %          contents=get(t,struct_element.contents);
1467 %          iline=iline+1;
1468 %          subelem(iline).xsindex=k;
1469 %          subelem(iline).index=1;
1470 % %          subelem(iline).testmanual=element.testmanual;%
1471 %          if isfield(contents,'value') & ~isempty(contents.value)
1472 %              subelem(iline).val=contents.value;
1473 %          elseif xs_subelem(k).testsub
1474 %              subelem(iline).val='';
1475 %          elseif isequal(xs_subelem(k).minOccurs,0)
1476 %              subelem(iline).val='[]';%element value not mandatory in the schema
1477 %          else
1478 %              subelem(iline).val='[MISSING]';%element value mandatory in the schema
1479 %          end
1480 % %          subelem(iline).attrup=attrup; %inheritated attributes
1481 %          if isfield(struct_element,'attributes')
1482 %             element_attr=struct_element.attributes;
1483 %             attr_display=[];
1484 %             for iattr=1:length(element_attr)
1485 % %                 attr_display{iline}=[attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
1486 %                 subelem(iline).val=[subelem(iline).val attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
1487 % %                 subelem(iline).attrup=setfield(subelem(iline).attrup,element_attr{iattr}.key,element_attr{iattr}.val);
1488 %             end
1489 %          end
1490 %      else%case of a multiple element
1491 %          for subindex=1:length(struct_element)
1492 %              contents=get(t,struct_element{subindex}.contents);
1493 %              iline=iline+1;
1494 %              subelem(iline).index=subindex;%index of the element
1495 %              subelem(iline).xsindex=k;
1496 % %              subelem(iline).testmanual=element.testmanual;%
1497 %              if isfield(contents,'value')& ~isempty(contents.value)
1498 %                  subelem(iline).val=contents.value;
1499 %              elseif xs_subelem(k).testsub
1500 %                  subelem(iline).val='';
1501 %              else
1502 %                  subelem(iline).val='[]';
1503 %              end
1504 % %              subelem(iline).attrup=attrup; %inheritated attributes
1505 %              if isfield(struct_element{subindex},'attributes')
1506 %                 element_attr=struct_element{subindex}.attributes;
1507 %                 attr_display=[];
1508 %                 for iattr=1:length(element_attr)
1509 % %                     attr_display{iline}=[attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
1510 %                     subelem(iline).val=[subelem(iline).val attr_display ' , ' element_attr{iattr}.key '  =  ' element_attr{iattr}.val];
1511 % %                     subelem(iline).attrup=setfield(subelem(iline).attrup,element_attr{iattr}.key,element_attr{iattr}.val);
1512 %                 end
1513 %             end
1514 %         end
1515 %      end
1516 %   end
1517 % end
1518
1519
1520 % --- Executes on button press in HELP.
1521 function HELP_Callback(hObject, eventdata, handles)
1522 path_to_uvmat=which ('uvmat')% check the path of uvmat
1523 pathelp=fileparts(path_to_uvmat);
1524 helpfile=fullfile(pathelp,'UVMAT_DOC','uvmat_doc.html');
1525 if isempty(dir(helpfile)), errordlg('Please put the help file uvmat_doc.html in the directory UVMAT/UVMAT_DOC')
1526 else
1527 web([helpfile '#editxml'])
1528 end
1529
1530
1531 % --- Executes on button press in Export.
1532 function Export_Callback(hObject, eventdata, handles)
1533 val=get(handles.Export,'Value');
1534 if val
1535     set(handles.Export,'BackgroundColor',[0 1 0])
1536     set(handles.export_list,'Visible','on')
1537     set(handles.replicate,'Visible','on')
1538     h_dataview=findobj(allchild(0),'name',dataview');
1539     if isempty(h_dataview)
1540        % CurrentFile=get(handles.CurrentFile,'String');
1541         dataview;
1542     end
1543 else
1544      set(handles.Export,'BackgroundColor',[0.7 0.7 0.7])
1545     set(handles.export_list,'Visible','off')
1546     set(handles.replicate,'Visible','off')
1547 end
1548
1549
1550 % --- Executes on button press in pushbutton9.
1551 function pushbutton9_Callback(hObject, eventdata, handles)
1552 % hObject    handle to pushbutton9 (see GCBO)
1553 % eventdata  reserved - to be defined in a future version of MATLAB
1554 % handles    structure with handles and user data (see GUIDATA)
1555
1556