Description of griddata_uvmat
Home > . > griddata_uvmat.m
griddata_uvmat
PURPOSE
'griddata_uvmat': function griddata_uvmat(vec2_X,vec2_Y,vec2_U,vec_X,vec_Y,'linear')
SYNOPSIS
function ZI = griddata_uvmat(X,Y,Z,XI,YI)
DESCRIPTION
'griddata_uvmat': function griddata_uvmat(vec2_X,vec2_Y,vec2_U,vec_X,vec_Y,'linear')
adapt the input of the matlab function griddata to the appropriate version of Matlab
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
RUN_FIX 'RUN_FIX': function for fixing velocity fields:
RUN_STLIN 'RUN_STLIN': combine velocity fields for stereo PIV
proj_field 'proj_field': projects the field on a projection object
proj_grid 'proj_grid': project fields with unstructured coordinantes on a regular grid
sub_field 'sub_field': combines two input fields + mask for uvmat
SOURCE CODE
%'griddata_uvmat': function griddata_uvmat(vec2_X,vec2_Y,vec2_U,vec_X,vec_Y,'linear')
%adapt the input of the matlab function griddata to the appropriate version of Matlab
function ZI = griddata_uvmat(X,Y,Z,XI,YI)
txt=ver;
Release=txt(1).Release;
relnumb=str2num(Release(3:4));
if relnumb >= 14
    ZI=griddata(X,Y,Z,XI,YI,'linear',{'QJ'});
else
    ZI=griddata(X,Y,Z,XI,YI,'linear');
end