Description of imadoc2struct
Home > . > imadoc2struct.m
imadoc2struct
PURPOSE
'imadoc2struct': reads the xml file for image documentation
SYNOPSIS
function [s,errormsg]=imadoc2struct(ImaDoc)
DESCRIPTION
'imadoc2struct': reads the xml file for image documentation
function [s,errormsg]=imadoc2struct(ImaDoc)
--------------------------------------------------------
 OUTPUT:
 s: structutre representing ImaDoc
 errormsg: error message
 INPUT:
 ImaDoc: full name of the xml input file with head key ImaDoc
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
RUN_STLIN 'RUN_STLIN': combine velocity fields for stereo PIV
civ 'civ': function associated with the interface 'civ.fig' for PIV, spline interpolation and stereo PIV (patch)
civ_3D 'civ_3D': function associated with the interface 'civ_3D.fig' for PIV in volume
series 'series': master function associated to the GUI series.m for analysis field series
set_grid 'set_grid':produce grid for PIV with one or two images (stereo case)
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SUBFUNCTIONS
function abs_time=get_time(BurstTiming)
function tsai=get_GeometryCalib(s)
SOURCE CODE
%'imadoc2struct': reads the xml file for image documentation
%
%function [s,errormsg]=imadoc2struct(ImaDoc)
%--------------------------------------------------------
% OUTPUT:
% s: structutre representing ImaDoc
% errormsg: error message
%
% INPUT:
% ImaDoc: full name of the xml input file with head key ImaDoc
function [s,errormsg]=imadoc2struct(ImaDoc)
s=[];
errormsg=[];%default
try
    t=xmltree(ImaDoc);
catch
    errormsg={[ImaDoc ' is not a valid xml file']; lasterr};
    display(errormsg);
    return
end
RootKey=get(t,1,'name');
if ~isequal(RootKey,'ImaDoc')
    errormsg=[ImaDoc ' is not an image documentation file'];
    return
end
s=convert(t);
s.Time=[];%default
if isfield(s,'Camera')
    if isfield(s.Camera,'BurstTiming')
        s.Time=get_time(s.Camera.BurstTiming);
        s.Camera=rmfield(s.Camera,'BurstTiming');
    end
end
if isfield(s,'GeometryCalib')
    s.GeometryCalib=get_GeometryCalib(s.GeometryCalib);
end
%----------------------------------------
function abs_time=get_time(BurstTiming)
abs_time=[];
for k=1:length(BurstTiming)
    Frequency=1;%default
    if isfield(BurstTiming,'FrameFrequency')&&~isempty(BurstTiming.FrameFrequency)
        Frequency=str2double(BurstTiming.FrameFrequency);
    end
    Dtj=[];%default
    if isfield(BurstTiming,'Dtj')
       Dtj=str2num(BurstTiming.Dtj);
    end
    NbDtj=1;%default
    if isfield(BurstTiming,'NbDtj')&&~isempty(BurstTiming.NbDtj)
        NbDtj=str2double(BurstTiming.NbDtj);
    end
    Dti=[]; %default
    if isfield(BurstTiming,'Dti')
        Dti=str2num(BurstTiming.Dti);
    end
    NbDti=1;%default
    if isfield(BurstTiming,'NbDti')&&~isempty(BurstTiming.NbDti)
       NbDti=str2double(BurstTiming.NbDti);
    end
    if ~isempty(Dtj)
        Dtj=reshape(Dtj'*ones(1,NbDtj),1,length(Dtj)*NbDtj);
    end
    Dtj=[0 Dtj];
    dtunit=Dtj/Frequency;
    Time=[];%default
    if isfield(BurstTiming,'Time') && ~isempty(BurstTiming.Time)
        %nbfield=length(BurstTiming.Time)
        if ischar(BurstTiming.Time)
             Time(1,1)=str2num(BurstTiming.Time);
             nbfield=1;
        else
            nbfield=length(BurstTiming.Time);
             for itime=1:nbfield
                 Time(itime,1)=str2num(BurstTiming.Time{itime});
             end
        end
        abstime_read=Time*ones(1,length(Dtj))+ones(nbfield,1)*cumsum(dtunit);
        abs_time=[abs_time;abstime_read];
        if ~isempty(Dti) && size(abs_time,1)==1
           abs_time=ones(NbDti+1,1)*abs_time+(Dti/Frequency)*(0:NbDti)'*ones(size(abs_time));
        end
    end
end
%----------------------------------------------------------------
function tsai=get_GeometryCalib(s)
%default values:
tsai.f=1;
tsai.dpx=1;
tsai.dpy=1;
tsai.sx=1;
tsai.Cx=0;
tsai.Cy=0;
tsai.Tx=0;
tsai.Ty=0;
tsai.Tz=1;
tsai.R=[1 0 0; 0 1 0; 0 0 0];
tsai.kappa1=0;
if isfield(s,'focal')
    tsai.f=str2double(s.focal);
end
if isfield(s,'dpx_dpy')
    dpx_dpy=str2num(s.dpx_dpy);
    tsai.dpx=dpx_dpy(1);
    tsai.dpy=dpx_dpy(2);
end
if isfield(s,'sx')
    tsai.sx=str2double(s.sx);
end
if isfield(s,'Cx_Cy')
    Cx_Cy=str2num(s.Cx_Cy);
    tsai.Cx=Cx_Cy(1);
    tsai.Cy=Cx_Cy(2);
end
if isfield(s,'Tx_Ty_Tz')
    Tx_Ty_Tz=str2num(s.Tx_Ty_Tz);
    tsai.Tx=Tx_Ty_Tz(1);
    tsai.Ty=Tx_Ty_Tz(2);
    tsai.Tz=Tx_Ty_Tz(3);
end
if isfield(s,'R')
    tsai.R=[str2num(s.R{1});str2num(s.R{2});str2num(s.R{3})];
end
if isfield(s,'kappa1')
    tsai.kappa1=str2double(s.kappa1);
end
if isfield(s,'SliceOrigin')
    if ischar(s.SliceOrigin)
        tsai.SliceOrigin=str2num(s.SliceOrigin);
    end
end
if isfield(s,'SliceDZ')
%     SliceOrigin=0;
%     SliceOZ=1;%default
    NbSlice=1;%default
    if ischar(s.NbSlice)
        NbSlice=str2double(s.NbSlice);
    end
    if ischar(s.SliceOrigin)
        SliceOrigin=str2num(s.SliceOrigin);
        if length(SliceOrigin)==3
            tsai.SliceCoord(1,:)=SliceOrigin;%to generalize for angles
        end
    end
    if ischar(s.SliceDZ)
        SliceOZ=str2double(s.SliceDZ);
        tsai.SliceCoord=tsai.SliceZ+SliceOZ*(0:NbSlice-1);
    end
    if iscell(s.SliceDZ)
        for j=1:length(s.SliceDZ)
            tsai.SliceCoord(j,:)=tsai.SliceZ(j-1,:)+str2num(s.SliceDZ{j});
        end
    end
end
if isfield(s,'PlanePos')%Obsolete
    if ischar(s.PlanePos)
        tsai.SliceCoord(1,:)=str2num(s.PlanePos);
    else
        for j=1:length(s.PlanePos)
            PlanePos=str2num(s.PlanePos{j});
            tsai.SliceCoord(j,:)=PlanePos;
        end
    end
end
%look for laser plane definitions