Description of read_image
Home > . > read_image.m
read_image
PURPOSE
'read_image': reads an image from a single file or a movie file
SYNOPSIS
function [A,error]=read_image(filename,NomType,num);
DESCRIPTION
'read_image': reads an image from a single file or a movie file
read  images in different formats.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
civ 'civ': function associated with the interface 'civ.fig' for PIV, spline interpolation and stereo PIV (patch)
civ_3D 'civ_3D': function associated with the interface 'civ_3D.fig' for PIV in volume
series 'series': master function associated to the GUI series.m for analysis field series
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SOURCE CODE
%'read_image': reads an image from a single file or a movie file
function [A,error]=read_image(filename,NomType,num);
 %read  images in different formats.
A=[]; %default
error=0; %default
if ~exist(filename,'file')
    error='input file not found in read_image'
    return
end
testframe=0;
if ~exist('NomType','var')
    NomType=[];
end
if ~exist('num','var')
    num=1;
end
[pth,fl,ext]=fileparts(filename);
if isequal(lower(ext),'.avi')
    mov=aviread(filename,num);
    A=frame2im(mov(1));
elseif isequal(lower(ext),'.vol')
     A=imread(filename);
else
     form=imformats(ext([2:end]));
     if ~isempty(form)% if the extension corresponds to an image format recognized by Matlab
         if isequal(NomType,'*');
            A=imread(filename,num);
         else
           A=imread(filename);
         end
     else
         error=['ERROR in read_image: file extension not recognized by matlab as image'];
         return
     end
end