Description of read_var_names
Home > coriolis > bigone > PROJETS > UVMAT.new > read_var_names.m
read_var_names
PURPOSE
'read_var_names': read the list of selected variables from the GUI get_field (SAME AS THE FIRST
SYNOPSIS
function SubField=read_var_names(handles)
DESCRIPTION
'read_var_names': read the list of selected variables from the GUI get_field (SAME AS THE FIRST
 PART OF plot_callback
---------------------------------------------------------
 global SubField
CROSS-REFERENCE INFORMATION
This function calls:
warndlg_uvmat 'warndlg_uvmat': display warning message (error, warning, confirmation) in a given figure
This function is called by:
series 'series': master function associated to the GUI series.m for analysis field series
uvmat 'uvmat': function associated with the interface 'uvmat.fig' for images and field visualization