Description of read_get_field
Home > . > read_get_field.m
read_get_field
PURPOSE
'read_get_field': read the list of selected variables from the GUI get_field (SAME AS THE FIRST
SYNOPSIS
function [SubField,errormsg]=read_get_field(hget_field)
DESCRIPTION
'read_get_field': read the list of selected variables from the GUI get_field (SAME AS THE FIRST
 INPUT:
 hget_field: handles of the GUI get_field
CROSS-REFERENCE INFORMATION
This function calls:
nc2struct 'nc2struct': transform a netcdf file in a corresponding matlab structure
This function is called by:
get_field 'get_field': display variables and attributes from a Netcdf file, and plot selected fields
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SUBFUNCTIONS
function VarIndex_y=name2index(cell_str,ListVarName)
SOURCE CODE
%'read_get_field': read the list of selected variables from the GUI get_field (SAME AS THE FIRST
% INPUT:
% hget_field: handles of the GUI get_field
function [SubField,errormsg]=read_get_field(hget_field)
%---------------------------------------------------------
SubField=[];%default
errormsg=[]; %default
handles=guidata(hget_field);%handles of GUI elements in get_field
Field=get(hget_field,'UserData');% read the current field Structure in the get_field interface
if isfield(Field,'VarAttribute')
    VarAttribute=Field.VarAttribute;
else
    VarAttribute={};
end
% select the indices of field variables for 2D plots
test_1Dplot=get(handles.check_1Dplot,'Value');
test_scalar=get(handles.check_scalar,'Value');
test_vector=get(handles.check_vector,'Value');
nbvar=0;
empty_coord_x=0;
empty_coord_y=0;
dimname_y={};
ListVarName={};
VarDimName={};
SubVarAttribute={};
dim_x=0;
dim_y=0;
dim_z=0;
dim_vec_x=0;
dim_vec_y=0;
dim_vec_z=0;
c_index=[];
if test_1Dplot
     % select ordinate variable(s)
    inputlist=get(handles.ordinate,'String');
    val=get(handles.ordinate,'Value');% selection(s) for ordinate
    VarNameCell=inputlist(val); %names of the variable(s) in the list
    for ivar=1:length(VarNameCell)
        VarIndex=name2index(VarNameCell{ivar},Field.ListVarName);%index of the variable in ListVarName
        dimname_y{ivar}=Field.VarDimName{VarIndex};% name of the corresponding dimension
        if iscell(dimname_y{ivar})
            dimname_y{ivar}=dimname_y{ivar}{1};%take the first dimension in case of a matrix
        end
        if ~strcmp(dimname_y{1},dimname_y{ivar})
            errormsg='unequal dimensions for the set of selected ordinate variables';
            return
        end
        nbvar=nbvar+1;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=Field.VarDimName{VarIndex};
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        SubVarAttribute{nbvar}.Role='scalar';
    end
    field_var_index=VarIndex; %store the last variable index to determine the absissa dimension if not defiend
        % select abscissa variable
    inputlist=get(handles.abscissa,'String');
    val=get(handles.abscissa,'Value');% a single selection is expected for abscissa
    VarName=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
%     dimname_x=[];%default
    if isempty(VarIndex)% default abscissa = matrix index
        coord_x_name=dimname_y{1};% name of the x coordinate = dimension of the plotted quantity
        empty_coord_x=1;
    else
        dimname_x=Field.VarDimName{VarIndex};
        if numel(dimname_x)~=1
            errormsg='abscissa must be a one-dimensional variable';
            return
        end
        if ~isempty(dimname_x) && ~strcmp(dimname_y{1},dimname_x)
            errormsg='inconsistent dimensions for ordinate and abscissa';
            return
        end
        nbvar=nbvar+1;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=Field.VarDimName{VarIndex};
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        SubVarAttribute{nbvar}.Role='coord_x';
    end
end
test3D=strcmp(get(handles.coord_z_scalar,'Visible'),'on')||strcmp(get(handles.coord_z_vectors,'Visible'),'on');
A_index=[];
if test_scalar
    %scalar variable
    inputlist=get(handles.scalar,'String');
    if isempty(inputlist)
        errormsg='empty input field';
        return
    end
    val=get(handles.scalar,'Value');%selected indices in the ordinate listbox
    VarNameScalar=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarNameScalar,Field.ListVarName);%index of the variable in ListVarName
    dimname_A=Field.VarDimName{VarIndex};
    nbvar=nbvar+1;
    ListVarName{nbvar}=Field.ListVarName{VarIndex};
    A_index=nbvar;
    VarDimName{nbvar}=dimname_A;
    SubVarAttribute{nbvar}=VarAttribute{VarIndex};
    SubVarAttribute{nbvar}.Role='scalar';
    field_var_index=VarIndex; %store the last variable index to determine the absissa dimension if not defiend
     % select x variable
    inputlist=get(handles.coord_x_scalar,'String');
    val=get(handles.coord_x_scalar,'Value');% a single selection is expected for abscissa
    VarName=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
    if isempty(VarIndex)% default abscissa = matrix index
        coord_x_name=dimname_A{2};% name of the x coordinate = dimension of the plotted quantity
        empty_coord_x=1;
    else
        dimname_x=Field.VarDimName{VarIndex};
         %check consistency of dimensions
        if ~isequal(dimname_x,dimname_A)% case of dimension variables
            for icoord=1:numel(dimname_A)% look for coincidence of dimension with one of the dimensions of the scalar
                if strcmp(dimname_x,dimname_A{icoord})% a dimension variable
                    dim_x=icoord;
                    break
                end
            end
            if ~dim_x
                errormsg='inconsistent dimensions for coordinate x';
                return
            end
        end
        nbvar=nbvar+1;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=dimname_x;
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        if dim_x
            SubVarAttribute{nbvar}.Role='dimvar';% dimension variable
        else
            SubVarAttribute{nbvar}.Role='coord_x';%abcissa with unstructured coordinates
        end
    end
    % select y variable
    inputlist=get(handles.coord_y_scalar,'String');
    val=get(handles.coord_y_scalar,'Value');% a single selection is expected for abscissa
    VarName=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
    if isempty(VarIndex)% default abscissa = matrix index
        coord_y_name=dimname_A{1};% name of the x coordinate = dimension of the plotted quantity
        empty_coord_y=1;
    else
        dimname_y=Field.VarDimName{VarIndex};
         %check consistency of dimensions
        if ~isequal(dimname_y,dimname_A)
            for icoord=1:numel(dimname_A)
                if strcmp(dimname_y,dimname_A{icoord})%  a dimension variable
                     dim_y=icoord;
                    break
                end
            end
            if ~dim_y
                errormsg='inconsistent dimensions for coordinate x';
                return
            end
        end
        nbvar=nbvar+1;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=dimname_y;
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        if dim_y
            SubVarAttribute{nbvar}.Role='dimvar';% dimension variable
        else
            SubVarAttribute{nbvar}.Role='coord_y';%ordinate with unstructured coordinates
        end
    end
        % select z variable
   if test3D
        inputlist=get(handles.coord_z_scalar,'String');
        val=get(handles.coord_z_scalar,'Value');% a single selection is expected for abscissa
        VarName=inputlist{val}; %name of the variable in the list
        VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
        if isempty(VarIndex)% default abscissa = matrix index
%             coord_z_name=dimname_A{1};% name of the x coordinate = dimension of the plotted quantity
            empty_coord_z=1;
        else
            dimname_z=Field.VarDimName{VarIndex};
             %check consistency of dimensions
            if ~isequal(dimname_z,dimname_A)
                for icoord=1:numel(dimname_A)
                    if strcmp(dimname_z,dimname_A{icoord})%  a dimension variable
                         dim_z=icoord;
                        break
                    end
                end
                if ~dim_z
                    errormsg='inconsistent dimensions for coordinate z';
                    return
                end
            end
            nbvar=nbvar+1;
            ListVarName{nbvar}=Field.ListVarName{VarIndex};
            VarDimName{nbvar}=dimname_z;
            SubVarAttribute{nbvar}=VarAttribute{VarIndex};
            if dim_z
                SubVarAttribute{nbvar}.Role='dimvar';% dimension variable
            else
                SubVarAttribute{nbvar}.Role='coord_z';%z coordinate with unstructured coordinates
            end
        end
   end
end
if test_vector
    %select u variable
    inputlist=get(handles.vector_x,'String');
    if isempty(inputlist)
        errormsg='empty input field';
        return
    end
    val=get(handles.vector_x,'Value');%selected indices in the ordinate listbox
    VarNameU=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarNameU,Field.ListVarName);%index of the variable in ListVarName
    nbvar=nbvar+1;
    u_index=nbvar;
    ListVarName{nbvar}=Field.ListVarName{VarIndex};
    dimname_u=Field.VarDimName{VarIndex};
    VarDimName{nbvar}=dimname_u;
    SubVarAttribute{nbvar}=VarAttribute{VarIndex};
    SubVarAttribute{nbvar}.Role='vector_x';
    field_var_index=VarIndex; %store the last variable index to determine the absissa dimension if not defiend
    %scalar v variable
    inputlist=get(handles.vector_y,'String');
    val=get(handles.vector_y,'Value');%selected indices in the ordinate listbox
    VarNameV=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarNameV,Field.ListVarName);%index of the variable in ListVarName
     %check consistency of dimensions with u
    dimname_v=Field.VarDimName{VarIndex};
    if ~isequal(dimname_v,dimname_u)
       errormsg='inconsistent dimensions for u and v';
        return
    end
    nbvar=nbvar+1;
    v_index=nbvar;
    ListVarName{nbvar}=Field.ListVarName{VarIndex};
    VarDimName{nbvar}=dimname_u;
    SubVarAttribute{nbvar}=VarAttribute{VarIndex};
    SubVarAttribute{nbvar}.Role='vector_y';
     % select x variable
    inputlist=get(handles.coord_x_vectors,'String');
    val=get(handles.coord_x_vectors,'Value');% a single selection is expected for abscissa
    VarName=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
    if isempty(VarIndex)% default abscissa = matrix index
        coord_x_name=dimname_u{2};% name of the x coordinate = dimension of the plotted quantity
        empty_coord_x=1;
    else
        if ~isequal(Field.VarDimName{VarIndex},dimname_u)
            for icoord=1:numel(dimname_u)
                if strcmp(Field.VarDimName{VarIndex},dimname_u{icoord})% x not a dimension variable
                    dim_vec_x=icoord;
                    break
                end
            end
            if ~dim_vec_x
                errormsg='inconsistent dimensions for u and x' ;
                return
            end
        end
        nbvar=nbvar+1;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=Field.VarDimName{VarIndex};
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        if dim_vec_x
            SubVarAttribute{nbvar}.Role='dimvar';% dimension variable
        else
            SubVarAttribute{nbvar}.Role='coord_x';%absissa with unstructured coordinates
        end
    end
      % select y variable
    inputlist=get(handles.coord_y_vectors,'String');
    val=get(handles.coord_y_vectors,'Value');% a single selection is expected for abscissa
    VarName=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
            %check consistency of dimensions
    if isempty(VarIndex)% default abscissa = matrix index
        coord_y_name=dimname_u{1};% name of the x coordinate = dimension of the plotted quantity
        empty_coord_y=1;
    else
        if ~isequal(Field.VarDimName{VarIndex},dimname_u)
            for icoord=1:numel(dimname_u)
                if strcmp(Field.VarDimName{VarIndex},dimname_u{icoord})% x not a dimension variable
                    dim_vec_y=1;
                    break
                end
            end
            if ~dim_vec_y
                errormsg='inconsistent dimensions for u and y';
                return
            end
        end
        nbvar=nbvar+1;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=Field.VarDimName{VarIndex};
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        if dim_vec_y
            SubVarAttribute{nbvar}.Role='dimvar';% dimension variable
        else
            SubVarAttribute{nbvar}.Role='coord_y';%ordinate with unstructured coordinates
        end
    end
          % select z variable
    if test3D
        inputlist=get(handles.coord_z_vectors,'String');
        val=get(handles.coord_z_vectors,'Value');% a single selection is expected for abscissa
        VarName=inputlist{val}; %name of the variable in the list
        VarIndex=name2index(VarName,Field.ListVarName);%index of the variable in ListVarName
                %check consistency of dimensions
        if isempty(VarIndex)% default abscissa = matrix index
            coord_z_name=dimname_u{1};% name of the x coordinate = dimension of the plotted quantity
            empty_coord_z=1;
        else
            if ~isequal(Field.VarDimName{VarIndex},dimname_u)
                for icoord=1:numel(dimname_u)
                    if strcmp(Field.VarDimName{VarIndex},dimname_u{icoord})% x not a dimension variable
                        dim_vec_z=icoord;
                        break
                    end
                end
                if ~dim_vec_z
                    errormsg='inconsistent dimensions for u and z';
                    return
                end
            end
            nbvar=nbvar+1;
            ListVarName{nbvar}=Field.ListVarName{VarIndex};
            VarDimName{nbvar}=Field.VarDimName{VarIndex};
            SubVarAttribute{nbvar}=VarAttribute{VarIndex};
            if dim_vec_z
                SubVarAttribute{nbvar}.Role='dimvar';% dimension variable
            else
                SubVarAttribute{nbvar}.Role='coord_z';%ordinate with unstructured coordinates
            end
        end
         %scalar w variable
        inputlist=get(handles.vector_z,'String');
        val=get(handles.vector_z,'Value');%selected indices in the ordinate listbox
        VarNameW=inputlist{val}; %name of the variable in the list
        VarIndex=name2index(VarNameW,Field.ListVarName);%index of the variable in ListVarName
         %check consistency of dimensions with u
        dimname_w=Field.VarDimName{VarIndex};
        if ~isequal(dimname_w,dimname_u)
           errormsg='inconsistent dimensions for u and v';
            return
        end
        nbvar=nbvar+1;
        w_index=nbvar;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=dimname_u;
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        SubVarAttribute{nbvar}.Role='vector_z';
    end
    % select color variable
    inputlist=get(handles.vec_color,'String');
    val=get(handles.vec_color,'Value');% a single selection is expected for abscissa
    VarNameC=inputlist{val}; %name of the variable in the list
    VarIndex=name2index(VarNameC,Field.ListVarName);%index of the variable in ListVarName
       %check consistency of dimensions with u
    if ~isempty(VarIndex)
        if ~isequal(Field.VarDimName{VarIndex},dimname_u)
            errormsg='inconsistent dimensions for u and v';
            return
        end
        nbvar=nbvar+1;
        c_index=nbvar;
        ListVarName{nbvar}=Field.ListVarName{VarIndex};
        VarDimName{nbvar}=Field.VarDimName{VarIndex};
        SubVarAttribute{nbvar}=VarAttribute{VarIndex};
        SubVarAttribute{nbvar}.Role='scalar';
    end
end
% get the input field
inputfield=get(handles.inputfile,'String');
if exist(inputfield,'file')% read the input data corresponding to the list of selected varaibles
    SubField=nc2struct(inputfield,ListVarName);
else  % subfield stored in memory
    SubField.ListVarName=ListVarName;
    SubField.VarDimName=VarDimName;
end
SubField.ListGlobalAttribute=['InputFile' SubField.ListGlobalAttribute];
SubField.InputFile=get(handles.inputfile,'String');
SubField.VarAttribute=SubVarAttribute;
%permute indices if coord_y is not the first matrix index
if dim_x && dim_y && ~isempty(A_index)
    DimCell=SubField.VarDimName{A_index};
    if dim_z
        DimCell(1:3)=DimCell([dim_z dim_y dim_x]);
        dim_end=[4:numel(DimCell)];
        eval(['SubField.' VarNameScalar '=permute(SubField.' VarNameScalar ',[dim_z dim_y dim_x dim_end]);'])
    else
        DimCell(1:2)=DimCell([dim_y dim_x]);
        dim_end=[3:numel(DimCell)];
        eval(['SubField.' VarNameScalar '=permute(SubField.' VarNameScalar ',[dim_y dim_x dim_end]);'])
    end
    SubField.VarDimName{A_index}=DimCell;
end
%permute indices if ccord_y is not the first matrix index
if dim_vec_x && dim_vec_y && ~isempty(u_index)
    DimCell=SubField.VarDimName{u_index};
    if dim_vec_z
        DimCell(1:3)=DimCell([dim_vec_z dim_vec_y dim_vec_x]);
        dim_end=[4:numel(DimCell)];
        eval(['SubField.' VarNameU '=permute(SubField.' VarNameU ',[dim_z dim_y dim_x dim_end]);'])
        eval(['SubField.' VarNameV '=permute(SubField.' VarNameV ',[dim_z dim_y dim_x dim_end]);'])
        eval(['SubField.' VarNameW '=permute(SubField.' VarNameW ',[dim_z dim_y dim_x dim_end]);'])
        if ~isempty(c_index)
            eval(['SubField.' VarNameC '=permute(SubField.' VarNameC ',[dim_z dim_y dim_x dim_end];]);'])
            SubField.VarDimName{c_index}=DimCell;
        end
        SubField.VarDimName{w_index}=DimCell;
    else
        DimCell(1:2)=DimCell([dim_vec_y dim_vec_x]);
        dim_end=[3:numel(DimCell)];
        eval(['SubField.' VarNameU '=permute(SubField.' VarNameU ',[dim_y dim_x dim_end];]);'])
        eval(['SubField.' VarNameV '=permute(SubField.' VarNameV ',[dim_y dim_x dim_end];]);'])
        if ~isempty(c_index)
            eval(['SubField.' VarNameC '=permute(SubField.' VarNameC ',[dim_y dim_x dim_end];]);'])
            SubField.VarDimName{c_index}=DimCell;
        end
    end
    SubField.VarDimName{u_index}=DimCell;
    SubField.VarDimName{v_index}=DimCell;
end
%add default coord_x and/or coord_y if empty
if empty_coord_x || empty_coord_y
    VarName=Field.ListVarName{field_var_index};
    eval(['npxy=size(SubField.' VarName ');'])
    Coord_1=[1 npxy(1)];
    Coord_2=[1 npxy(2)];
    testold=0;
%old convention; use of coord_1 and Coord_2
    if isfield(Field,'VarAttribute') && numel(Field.VarAttribute)>=field_var_index
        if isfield(Field.VarAttribute{field_var_index},'Coord_2')&& isfield(Field.VarAttribute{field_var_index},'Coord_1')
            Coord_2=Field.VarAttribute{field_var_index}.Coord_2;
            Coord_1=Field.VarAttribute{field_var_index}.Coord_1;
            testold=1;
        end
    end
    if empty_coord_x
        SubField.ListVarName=[{coord_x_name} SubField.ListVarName];
        SubField.VarDimName=[{coord_x_name} SubField.VarDimName];
        if test_scalar || test_vector %2D case
            eval(['SubField.' coord_x_name '=linspace(Coord_2(1),Coord_2(end),npxy(2));'])
        else % 1D plot
            eval(['SubField.' coord_x_name '=linspace(Coord_1(1),Coord_1(end),npxy(1));'])
        end
        if ~testold
            coord_x_attr.units='index';
        else
            coord_x_attr.units='cm';
        end
        SubField.VarAttribute=[{coord_x_attr} SubField.VarAttribute];
    end
    if empty_coord_y
        SubField.ListVarName=[{coord_y_name} SubField.ListVarName];
        SubField.VarDimName=[{coord_y_name} SubField.VarDimName];
        eval(['SubField.' coord_y_name '=linspace(Coord_1(1),Coord_1(end),npxy(1));'])
        if ~testold
            coord_y_attr.units='index';
        else
            coord_y_attr.units='cm';
        end
        SubField.VarAttribute=[{coord_y_attr} SubField.VarAttribute];
    end
end
%-------------------------------------------------
% give index numbers of the strings str in the list ListvarName
function VarIndex_y=name2index(cell_str,ListVarName)
VarIndex_y=[];
if ischar(cell_str)
    for ivar=1:length(ListVarName)
        varlist=ListVarName{ivar};
        if isequal(varlist,cell_str)
            VarIndex_y= ivar;
            break
        end
    end
elseif iscell(cell_str)
    for isel=1:length(cell_str)
        varsel=cell_str{isel};
        for ivar=1:length(ListVarName)
            varlist=ListVarName{ivar};
            if isequal(varlist,varsel)
                VarIndex_y=[VarIndex_y ivar];
            end
        end
    end
end