Description of set_title
Home > . > set_title.m
set_title
PURPOSE
'set_title': defines the 'TITLE' of a projection object
SYNOPSIS
function TITLE=set_title(Style,ProjMode)
DESCRIPTION
'set_title': defines the 'TITLE' of a projection object
-----------------------------------------------------------
 function TITLE=set_title(Style,ProjMode)
 OUTPUT:
    TITLE: char string defining the title
 INPUT:
    Style: char string defining the style of the projection opbject
    ProjMode:  char string defining the projection mode
------------------------------------------------
------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mouse_down 'mouse_down': function activated when the mouse button is pressed on a figure (callback for 'WindowButtonDownFcn'
plot_field 'plot_field': plot any field with the structure defined in the uvmat package
set_grid 'set_grid':produce grid for PIV with one or two images (stereo case)
set_object 'set_object': GUI to edit a projection object
update_obj 'update_obj': update the object graph representation and its projection field, record it in the uvmat interface
SOURCE CODE
%'set_title': defines the 'TITLE' of a projection object
%-----------------------------------------------------------
% function TITLE=set_title(Style,ProjMode)
% OUTPUT:
%    TITLE: char string defining the title
%
% INPUT:
%    Style: char string defining the style of the projection opbject
%    ProjMode:  char string defining the projection mode
%------------------------------------------------
function TITLE=set_title(Style,ProjMode)
%------------------------------------------------
TITLE=[]; %default
if isequal(Style,'points')
    TITLE='POINTS';
elseif isequal(Style,'line')|isequal(Style,'polyline')
    TITLE='LINE';
elseif isequal(Style,'plane')
    TITLE='PLANE';
elseif isequal(Style,'volume')
    TITLE='VOLUME';
elseif isequal(Style,'polygon')|isequal(Style,'rectangle')|isequal(Style,'ellipse')
    if isequal(ProjMode,'inside')|isequal(ProjMode,'outside')
        TITLE='PATCH';
    elseif isequal(ProjMode,'mask_inside')|isequal(ProjMode,'mask_outside')
        TITLE='MASK';
    else
        TITLE='LINE';
    end
end