Description of set_vec_col_bar
Home > coriolis > bigone > PROJETS > UVMAT.new > set_vec_col_bar.m
set_vec_col_bar
PURPOSE
update the display of color code for vectors
SYNOPSIS
function set_vec_col_bar(handles)
DESCRIPTION
update the display of color code for vectors
--------------------------------------------
get the image of the color display button 'vec_col_bar' in pixels
CROSS-REFERENCE INFORMATION
This function calls:
set_col_vec 'set_col_vec': sets the color code for vectors depending on a scalar vec_C and parameters given by the struct colcode
This function is called by:
uvmat 'uvmat': function associated with the interface 'uvmat.fig' for images and field visualization
write_plot_param 'write_plot_param': update the plotting parameters on the uvmat interface after a plotting operation