Description of sub_field
Home > . > sub_field.m
sub_field
PURPOSE
'sub_field': combines two input fields + mask for uvmat
SYNOPSIS
function SubData=sub_field(UvData,Field);
DESCRIPTION
'sub_field': combines two input fields + mask for uvmat
-----------------------------------------------------------------------
 function SubData=sub_field(UvData,Field)
 OUPUT:
 SubData: structure representing the resulting field
 INPUT:
 UvData: main structure UvData associated to the uvmat GUI as 'UserData'
 Field: cell of Matlab structures representing the input fields
    -- TODO: need to be rationalized --
CROSS-REFERENCE INFORMATION
This function calls:
calc_field 'calc_field': defines fields (velocity, vort, div...) from civx data and calculate them
griddata_uvmat 'griddata_uvmat': function griddata_uvmat(vec2_X,vec2_Y,vec2_U,vec_X,vec_Y,'linear')
proj_grid 'proj_grid': project fields with unstructured coordinantes on a regular grid
This function is called by:
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SOURCE CODE
%'sub_field': combines two input fields + mask for uvmat
%-----------------------------------------------------------------------
% function SubData=sub_field(UvData,Field)
%
% OUPUT:
% SubData: structure representing the resulting field
%
% INPUT:
% UvData: main structure UvData associated to the uvmat GUI as 'UserData'
% Field: cell of Matlab structures representing the input fields
%
%    -- TODO: need to be rationalized --
function SubData=sub_field(UvData,Field);
SubData=UvData;%default
if isfield(SubData,'ListVarName')
    SubData=rmfield(SubData,'ListVarName');
end
if ~exist('Field','var')
    return
end
if ~iscell(Field)
    return
end
nbfield=length(Field);
if nbfield==1 & isfield(Field{1},'ListVarName')
    SubData=Field{1};
    if isfield(UvData,'Object')
        SubData.Object=UvData.Object;
    end
    if isfield(UvData,'XmlData')
        SubData.XmlData=UvData.XmlData;
    end
    return
end
%transfer error messages
testerror=0;
if ~isfield(SubData,'Txt')
    for ifield=1:nbfield
        if isfield(Field{ifield},'Txt')
            SubData.Txt=Field{ifield}.Txt;
            testerror=1;
        end
    end
end
%fields
if nbfield >=1
   if isfield(Field{1},'dt')
       SubData.dt=Field{1}.dt;
   elseif isfield(SubData,'dt')
       SubData=rmfield(SubData,'dt');
   end
   if isfield(Field{1},'CoordType')
       SubData.CoordType=Field{1}.CoordType;
       %A FAIRE: Case of Field{2}.CoordType different
   end
    %background scalar
    if isfield(Field{1},'AName')
        SubData.AName=Field{1}.AName;
        if nbfield >=2 & isfield(Field{2},'AName')& ~isfield(Field{2},'A')
            SubData.Txt='ERROR: no substraction of background scalar';
        end
    elseif nbfield>=2 & isfield(Field{2},'AName')
        SubData.AName=Field{2}.AName;%transfer the second scalar or image field
    elseif isfield(SubData,'AName')
        SubData=rmfield(SubData,'AName');
    end
    testA=0;
    if isfield(Field{1},'A')& isfield(Field{1},'AX') & isfield(Field{1},'AY')
        SubData.A=Field{1}.A;
        SubData.AX=Field{1}.AX;
        SubData.AY=Field{1}.AY;
        if nbfield >=2 & isfield(Field{2},'A')& isfield(Field{2},'AX') & isfield(Field{2},'AY')
            if isequal(Field{2}.AX,Field{1}.AX) & isequal(Field{2}.AY,Field{1}.AY) &...
                              isequal(size(Field{2}.A),size(Field{1}.A))
                SubData.A=double(Field{1}.A)-double(Field{2}.A);
                if isa(Field{1}.A,'uint8')
                    SubData.A=int8(SubData.A);
                elseif isa(Field{1}.A,'uint16')
                    SubData.A=int16(SubData.A);%signed integer
                end
            else
                SubData.Txt='ERROR in image substraction: unequal image sizes';
            end
        end
        testA=1;
    elseif nbfield>=2 & isfield(Field{2},'A')& isfield(Field{2},'AX') & isfield(Field{2},'AY')
        SubData.A=Field{2}.A;%transfer the second scalar or image field
        SubData.AX=Field{2}.AX;
        SubData.AY=Field{2}.AY;
        testA=1;
    end
    if ~isfield(SubData,'NbDim')
        SubData.NbDim=2;%nbdim=2 by default
    end
%          if ~testA
        %coordinates
        ivel=1;
        if isfield(Field{1},'X')
            SubData.X=Field{1}.X;
        elseif nbfield>=2 & isfield(Field{2},'X')
            SubData.X=Field{2}.X;
            ivel=2;
        elseif isfield(SubData,'X')
            SubData=rmfield(SubData,'X');
        end
        if isfield(Field{ivel},'Y')
            SubData.Y=Field{ivel}.Y;
        elseif isfield(SubData,'Y')
            SubData=rmfield(SubData,'Y');
        end
        if isfield(Field{ivel},'Z')
            SubData.Z=Field{ivel}.Z;
            %don't remove Z (set by uvmat)
        end
        %velocity components and derived scalar
        if isfield(Field{ivel},'U')
            SubData.U=Field{ivel}.U;
        elseif isfield(SubData,'U')
            SubData=rmfield(SubData,'U');
        end
        if isfield(Field{ivel},'V')
            SubData.V=Field{ivel}.V;
        elseif isfield(SubData,'V')
            SubData=rmfield(SubData,'V');
        end
        if isfield(Field{ivel},'W')
            SubData.W=Field{ivel}.W;
        elseif isfield(SubData,'W')
            SubData=rmfield(SubData,'W');
        end
%          else
%              ivel=1;
%         end
    if nbfield>=2 & isfield(Field{2},'X') & ivel==1 %two velocity fields exist
        test_A=0;
        if isfield(Field{1},'A') ||(isfield(Field{1},'AName') && ~isempty(Field{1}.AName)) %if the first field is for a scalar
            if ~isfield(Field{1},'A')
                test_A=1;
                SubData.A=calc_field(Field{1}.AName,Field{1});
                SubData.AX=Field{1}.X;
                SubData.AY=Field{1}.Y;
                SubData.AName=Field{1}.AName;
                %remove false vectors
                if isfield(Field{1},'FF')
                    ind_sel=find(Field{1}.FF==0);%good indices
                    SubData.A=SubData.A(ind_sel);
                    SubData.AX=SubData.AX(ind_sel);
                    SubData.AY=SubData.AY(ind_sel);
                end
                [SubData.A,SubData.AX,SubData.AY]=...
                proj_grid(SubData.AX,SubData.AY,SubData.A,[],[],'np>256');
            end
        end
        if isfield(Field{2},'A')||(isfield(Field{2},'AName') && ~isempty(Field{2}.AName) )%if the second field is for a scalar
            testA=1;
            if ~isfield(Field{2},'A')
                A=calc_field(Field{2}.AName,Field{2});
                AX=Field{2}.X;
                AY=Field{2}.Y;
                AName=Field{2}.AName;
                %remove false vectors
                if isfield(Field{2},'FF')
                    ind_sel=find(Field{2}.FF==0);%good indices
                    A=A(ind_sel);
                    AX=AX(ind_sel);
                    AY=AY(ind_sel);
                end
                if test_A==1;%substract the two scalars
                    if SubData.NbDim==3
                        SubData.Txt='ERROR: no substraction of 3D fields';
                    elseif isequal(AName,SubData.AName)
                        [A,AX,AY]=proj_grid(AX,AY,A,SubData.AX,SubData.AY,size(SubData.A));
                        SubData.A=SubData.A-A;
                    else
                        SubData.Txt='ERROR: attempt to substract two scalars of different kind';
                    end
                else
                    [SubData.A,SubData.AX,SubData.AY]=proj_grid(AX,AY,A,[],[],'np>256');
                    SubData.AName=AName;
                    test_A=1;
                end
             end
         end
         if test_A==0% substract the velocity fields
            %A REVOIR cas 3 composantes 2D
            if isfield(Field{2},'FF')& ~isempty(Field{2}.FF)
                index2=find(Field{2}.FF==0);
                Field{2}.X=Field{2}.X(index2);
                Field{2}.Y=Field{2}.Y(index2);
                Field{2}.U=Field{2}.U(index2);
                Field{2}.V=Field{2}.V(index2);
            end
            if  ~isequal(Field{1}.X,Field{2}.X) | ~isequal(Field{1}.Y,Field{2}.Y); % if the vector positions are not the same
                Field{2}.U=griddata_uvmat(Field{2}.X,Field{2}.Y,Field{2}.U,Field{1}.X,Field{1}.Y);  %interpolate vectors in the second field
                Field{2}.V=griddata_uvmat(Field{2}.X,Field{2}.Y,Field{2}.V,Field{1}.X,Field{1}.Y); %  to the positions  of the first field
            end
            SubData.U=Field{1}.U-Field{2}.U;% take the interpolated first field - the second field
            SubData.V=Field{1}.V-Field{2}.V;
        end
    end
    %remove scalar data if no AName
    if ~testA%~isfield(SubData,'AName')
        if isfield(SubData,'A')
            SubData=rmfield(SubData,'A');
        end
        if isfield(SubData,'AX')
            SubData=rmfield(SubData,'AX');
        end
        if isfield(SubData,'AY')
            SubData=rmfield(SubData,'AY');
        end
    end
    if isfield(Field{ivel},'C')
        SubData.C=Field{ivel}.C;
    elseif isfield(SubData,'C')
        SubData=rmfield(SubData,'C');
    end
    if isfield(Field{ivel},'F')
        SubData.F=Field{ivel}.F;
    elseif isfield(SubData,'F')
        SubData=rmfield(SubData,'F');
    end
    if isfield(Field{ivel},'FF')
        SubData.FF=Field{ivel}.FF;
    elseif isfield(SubData,'FF')
        SubData=rmfield(SubData,'FF');
    end
    %velocity derivatives
    if isfield(Field{ivel},'DjUi')
        SubData.DjUi=Field{ivel}.DjUi;
    elseif isfield(SubData,'DjUi')
        SubData=rmfield(SubData,'DjUi');
    end
end