Description of update_menu
Home > . > update_menu.m
update_menu
PURPOSE
'update_menu': find an input string in a menu, add it to the menu at the penultimate position if it does not exist
SYNOPSIS
function menu_str=update_menu(handle,strinput)
DESCRIPTION
'update_menu': find an input string in a menu, add it to the menu at the penultimate position if it does not exist
-----------------------------------------------
 function menu_str=update_menu(handle,strinput)
 OUTPUT:
 menu_str: new menu; cell of strings
 INPUT:
 handle: handle of the menu to modify (listbox uicontrol)
 strinput: char string to detect or add in the menu
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_field 'get_field': display variables and attributes from a Netcdf file, and plot selected fields
series 'series': master function associated to the GUI series.m for analysis field series
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SOURCE CODE
%'update_menu': find an input string in a menu, add it to the menu at the penultimate position if it does not exist
%-----------------------------------------------
% function menu_str=update_menu(handle,strinput)
%
% OUTPUT:
% menu_str: new menu; cell of strings
%
% INPUT:
% handle: handle of the menu to modify (listbox uicontrol)
% strinput: char string to detect or add in the menu
function menu_str=update_menu(handle,strinput)
menu_str=get(handle,'String');
nbmenu=length(menu_str);
ichoice=0;%default
for imenu=1:nbmenu
    if isequal(menu_str{imenu},strinput)
       ichoice=imenu;
    end
end
if ichoice==0%the input string does not exist in the menu
    menu_str{nbmenu+1}=menu_str{nbmenu};%shift  the last item ('more...')
    menu_str{nbmenu}=strinput;
    set(handle,'String',menu_str)
    ichoice=nbmenu;
end
set(handle,'Value',ichoice)