Description of varname_generator
Home > coriolis > bigone > PROJETS > UVMAT.new > varname_generator.m
varname_generator
PURPOSE
'varname_generator': defines the names of constants and variable fields to read in the netcdf files
SYNOPSIS
function [cte,nb,var,vel_type_out]=varname_generator(vel_type,display,scal_name,scal_2,scal_3)
DESCRIPTION
'varname_generator': defines the names of constants and variable fields to read in the netcdf files
----------------------------------------------------------
 [cte,nb,var,vel_type_out]=varname_generator(vel_type,display,scal_name,scal_2,scal_3)
The names depend on the velocity type ('civ1',..) and scalar needed
CROSS-REFERENCE INFORMATION
This function calls:
calc_scal 'calc_scal': defines scalars and calculate them from stored fields. OBSOLETE to replace by calc_field
This function is called by:
RUN_STLIN 'RUN_STLIN': combine velocity fields for stereo PIV
read_ncfield 'read_ncfield': reads one or two velocity fields and associated parameters from a file .
read_scalar 'read_scalar': reads and calculates the vort div or any scalar from a file
read_vel 'read_vel': reads one or two velocity fields and associated parameters from a file or a pair of files.
series 'series': master function associated to the GUI series.m for analysis field series