Description of warndlg_uvmat
Home > . > warndlg_uvmat.m
warndlg_uvmat
PURPOSE
'warndlg_uvmat': display warning message (error, warning, confirmation) in a given figure
SYNOPSIS
function hwarn=warndlg_uvmat(warntext,title)
DESCRIPTION
'warndlg_uvmat': display warning message (error, warning, confirmation) in a given figure
---------------------------------------------------------------------
 hwarn=warndlg_uvmat(warntext,title)
---------------------------------------------------------------------
 OUTPUT:
 hwarn: string representing the file name (including path)
 INPUT:
 warntext: text to display
 title:  string indicating the type of message box:
          title= 'ERROR', 'WARNING', 'CONFIRMATION' .
CROSS-REFERENCE INFORMATION
This function calls:
msgbox_uvmat 'msgbox_uvmat': associated with GUI msgbox_uvmat.fig to display message boxes, for error, warning or input calls
This function is called by:
RUN_FIX 'RUN_FIX': function for fixing velocity fields:
RUN_STLIN 'RUN_STLIN': combine velocity fields for stereo PIV
civ 'civ': function associated with the interface 'civ.fig' for PIV, spline interpolation and stereo PIV (patch)
civ_3D 'civ_3D': function associated with the interface 'civ_3D.fig' for PIV in volume
dataview TEST 'dataview': function for scanning directories in a campaign (TEST)
editxml 'editxml': function for editing xml files using a xml schema (associated with the GUI editxml.fig)
geometry_calib 'geometry_calib': performs geometric calibration from a set of reference points
get_field 'get_field': display variables and attributes from a Netcdf file, and plot selected fields
plot_field 'plot_field': plot any field with the structure defined in the uvmat package
plot_object 'plot_object': draws a projection object (points, line, plane...)
probe_calib 'probe_calib': performs geometric calibration from a set of reference points
proj_field 'proj_field': projects the field on a projection object
proj_grid 'proj_grid': project fields with unstructured coordinantes on a regular grid
series 'series': master function associated to the GUI series.m for analysis field series
set_grid 'set_grid':produce grid for PIV with one or two images (stereo case)
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization
SOURCE CODE
%'warndlg_uvmat': display warning message (error, warning, confirmation) in a given figure
%---------------------------------------------------------------------
% hwarn=warndlg_uvmat(warntext,title)
%---------------------------------------------------------------------
% OUTPUT:
% hwarn: string representing the file name (including path)
%
% INPUT:
% warntext: text to display
% title:  string indicating the type of message box:
%          title= 'ERROR', 'WARNING', 'CONFIRMATION' .
function hwarn=warndlg_uvmat(warntext,title)
hwarn=msgbox_uvmat(title,warntext);
%if isequal(title,'ERROR')||isequal(title,'WARNING')
    %delete(hwarn)
%end