---
image: amd64/debian:stable-slim

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git zip

variables:
  GIT_DEPTH: 0

pages:
  stage: build
  script:
    - |
      mkdir -p public
      VERSION="$(date '+%y.%m').$(git rev-list --count HEAD)"
      echo "VERSION: ${VERSION}"
      git archive --format=zip \
        --prefix="UVMAT-${VERSION}/" \
        --output="public/UVMAT-${VERSION}.zip" HEAD
      ln -sf public/UVMAT-${VERSION}.zip public/UVMAT-Latest.zip
      cat EOL > public/index.html
      <ul>
      <li><a href=\"UVMAT-Latest.zip\">Download UVMAT (Latest)</a></li>
      <li><a href=\"UVMAT-${VERSION}.zip\">Download UVMAT (${VERSION})</a></li>
      </ul>
      EOL
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
