Description of civ_3D
Home > . > civ_3D.m
civ_3D
PURPOSE
'civ_3D': function associated with the interface 'civ_3D.fig' for PIV in volume
SYNOPSIS
function varargout = civ_3D(varargin)
DESCRIPTION
'civ_3D': function associated with the interface 'civ_3D.fig' for PIV in volume
------------------------------------------------------------------------
  provides an interface for the software CIVx
 function varargout = civ_3D(varargin)
 provides an interface for the software CIVx
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  Copyright Joel Sommeria, 2008, LEGI / CNRS-UJF-INPG, sommeria@coriolis-legi.org.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     This file is part of the toolbox UVMAT.
     UVMAT is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.
     UVMAT is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License (file UVMAT/COPYING.txt) for more details.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CROSS-REFERENCE INFORMATION
This function calls:
editxml 'editxml': function for editing xml files using a xml schema (associated with the GUI editxml.fig)
imadoc2struct 'imadoc2struct': reads the xml file for image documentation
msgbox_uvmat 'msgbox_uvmat': associated with GUI msgbox_uvmat.fig to display message boxes, for error, warning or input calls
name2display 'name2display': extracts the root name and field numbers from an input filename
name_generator 'name_generator': creates a file name from a root name and indices.
nc2struct 'nc2struct': transform a netcdf file in a corresponding matlab structure
num2stra 'num2stra': transform number to the corresponding character string depending on the nomenclature
read_image 'read_image': reads an image from a single file or a movie file
stra2num 'stra2num': transform letters (a, b, c) or numerical strings ('1','2'..) to the corresponding numbers
struct2xml 'struct2xml': transform a matlab structure to a xml tree.
This function is called by: