Description of proj_field
Home > . > proj_field.m
proj_field
PURPOSE
'proj_field': projects the field on a projection object
SYNOPSIS
function [ProjData,errormsg]=proj_field(FieldData,ObjectData,IndexObj)
DESCRIPTION
'proj_field': projects the field on a projection object
--------------------------------------------------------------------------
  function [ProjData,errormsg]=proj_field(FieldData,ObjectData,IndexObj)
 OUTPUT:
 ProjData structure containing the fields of the input field FieldData,
 transmitted or projected on the object, plus the additional fields
    .UMax, .UMin, .VMax, .VMin: min and max of velocity components in a domain
    .UMean,VMean: mean of the velocity components in a domain
    .AMin, AMax: min and max of a scalar
    .AMean: mean of a scalar in a domain
  .NbPix;
  .DimName=  names of the matrix dimensions (matlab cell)
  .DimValue= values of the matricx dimensions (matlab vector, same length as .DimName);
  .VarName= names of the variables [ProjData.VarName {'A','AMean','AMin','AMax'}];
  .VarDimNameIndex= dimensions of the variables, indicated by indices in the list .DimName;
INPUT
 ObjectData: structure characterizing the projection object
    .Style : style of projection object
    .ProjMode=type of projection ;
    .CoordType: 'px' or 'phys' type of coordinates defining the object position
    .Phi  angle of rotation (=0 by default)
    .ProjAngle=angle of projection;
    .DX,.DY,.DZ=increments along each coordinate
    .Coord(nbpoints,3): set of coordinates defining the object position;
CROSS-REFERENCE INFORMATION
This function calls:
find_field_indices 'find_file_indices': test field structure for input in proj_field and plot_field
griddata_uvmat 'griddata_uvmat': function griddata_uvmat(vec2_X,vec2_Y,vec2_U,vec_X,vec_Y,'linear')
msgbox_uvmat 'msgbox_uvmat': associated with GUI msgbox_uvmat.fig to display message boxes, for error, warning or input calls
This function is called by:
update_obj 'update_obj': update the object graph representation and its projection field, record it in the uvmat interface
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization