Description of read_plot_param
Home > . > read_plot_param.m
read_plot_param
PURPOSE
'read_plot_param': read plotting parameters from the interface uvmat
SYNOPSIS
function PlotParam=read_plot_param(handles)
DESCRIPTION
'read_plot_param':  read plotting parameters from the interface uvmat
------------------------------------------
 function PlotParam=read_plot_param(handles)
 OUTPUT:
 PlotParam: structure containing the values of all the relevant plotting parameters
 INPUT:
 handles: structure containing the handles of the relevant uicontrols in the uvmat interface
      -- TODO:   get the handles using get_plot_handles and findobj as  default input --
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mouse_down 'mouse_down': function activated when the mouse button is pressed on a figure (callback for 'WindowButtonDownFcn'
plot_field 'plot_field': plot any field with the structure defined in the uvmat package
uvmat 'uvmat': function associated with the GUI 'uvmat.fig' for images and data field visualization