Description of update_imadoc
Home > . > update_imadoc.m
update_imadoc
PURPOSE
'update_imadoc': update an xml file with geometric calibration parameters
SYNOPSIS
function update_imadoc(GeometryCalib,outputfile)
DESCRIPTION
'update_imadoc': update an xml file with geometric calibration parameters
--------------------------------------------------------------------------
  function update_imadoc(GeometryCalib,outputfile)
INPUT:
 GeometryCalib: structure containing the calibration parameters
 outputfile: xml file to modify
-------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
struct2xml 'struct2xml': transform a matlab structure to a xml tree.
This function is called by:
dataview 'dataview': function for scanning directories in a campaign
geometry_calib 'geometry_calib': performs geometric calibration from a set of reference points